import { VocabularyWord } from "./types";

export const KA_5A_5B_WORDS: VocabularyWord[] = [
    { id: '5a-5b-1', word: 'Symbolizes', definition: 'When one thing stands for a bigger idea (like a heart for love).', category: '5A-5B', exampleSentence: 'The dove symbolizes peace.', imageEmoji: '🕊️' },
    { id: '5a-5b-2', word: 'Exquisite', definition: 'Incredibly beautiful and well-made.', category: '5A-5B', exampleSentence: 'She wore an exquisite necklace.', imageEmoji: '💎' },
    { id: '5a-5b-3', word: 'Slurping', definition: 'Making a loud sucking noise while eating.', category: '5A-5B', exampleSentence: 'Stop slurping your soup!', imageEmoji: '🍜' },
    { id: '5a-5b-4', word: 'Breathtaking', definition: 'So amazing it takes your breath away.', category: '5A-5B', exampleSentence: 'The mountain view was breathtaking.', imageEmoji: '🏔️' },
    { id: '5a-5b-5', word: 'Elegant', definition: 'Fancy, graceful, and stylish.', category: '5A-5B', exampleSentence: 'The dancer was very elegant.', imageEmoji: '💃' },
    { id: '5a-5b-6', word: 'Colleagues', definition: 'The people you work with.', category: '5A-5B', exampleSentence: 'I went to lunch with my colleagues.', imageEmoji: '👔' },
    { id: '5a-5b-7', word: 'Stunning', definition: 'Extremely beautiful or shocking.', category: '5A-5B', exampleSentence: 'The sunset was stunning.', imageEmoji: '🌅' },
    { id: '5a-5b-8', word: 'Purified', definition: 'Made perfectly clean.', category: '5A-5B', exampleSentence: 'We drank purified water.', imageEmoji: '💧' },
    { id: '5a-5b-9', word: 'Affable', definition: 'Easy to talk to and very nice.', category: '5A-5B', exampleSentence: 'The new teacher is very affable.', imageEmoji: '😊' },
    { id: '5a-5b-10', word: 'Garbled', definition: "When words are so mixed up they don't make sense.", category: '5A-5B', exampleSentence: 'The radio message was garbled.', imageEmoji: '😵' },
    { id: '5a-5b-11', word: 'Absurd', definition: 'Completely silly or ridiculous.', category: '5A-5B', exampleSentence: 'That is an absurd idea!', imageEmoji: '🤪' },
    { id: '5a-5b-12', word: 'Roamed', definition: 'Wandered around without a set plan.', category: '5A-5B', exampleSentence: 'The buffalo roamed the plains.', imageEmoji: '🐃' },
    { id: '5a-5b-13', word: 'Destitute', definition: 'Being extremely poor with no money or home.', category: '5A-5B', exampleSentence: 'The war left many people destitute.', imageEmoji: '⛺' },
    { id: '5a-5b-14', word: 'Contribute', definition: 'To give your help or money to a group.', category: '5A-5B', exampleSentence: 'Everyone should contribute ideas.', imageEmoji: '🤝' },
    { id: '5a-5b-15', word: 'Abandoned', definition: 'Left all alone.', category: '5A-5B', exampleSentence: 'They found an abandoned puppy.', imageEmoji: '🏚️' },
    { id: '5a-5b-16', word: 'Embraced', definition: 'Gave a big hug or accepted an idea.', category: '5A-5B', exampleSentence: 'She embraced her friend warmly.', imageEmoji: '🤗' },
    { id: '5a-5b-17', word: 'Gratefully', definition: 'With a very thankful heart.', category: '5A-5B', exampleSentence: 'He accepted the gift gratefully.', imageEmoji: '🙏' },
    { id: '5a-5b-18', word: 'Revived', definition: 'Brought back to life or gave new energy.', category: '5A-5B', exampleSentence: 'The rain revived the wilting plants.', imageEmoji: '🌱' },
    { id: '5a-5b-19', word: 'Delighted', definition: 'Feeling very happy and joyful.', category: '5A-5B', exampleSentence: 'I am delighted to meet you.', imageEmoji: '🤩' },
    { id: '5a-5b-20', word: 'Wad', definition: 'A thick stack or lump of something (like money).', category: '5A-5B', exampleSentence: 'He had a wad of cash in his pocket.', imageEmoji: '💵' },
    { id: '5a-5b-21', word: 'Cynical', definition: 'Thinking that people are usually being selfish.', category: '5A-5B', exampleSentence: 'Don\'t be so cynical about everything.', imageEmoji: '😒' },
    { id: '5a-5b-22', word: 'Bleak', definition: 'Cold, empty, and hopeless.', category: '5A-5B', exampleSentence: 'The future looked bleak for the team.', imageEmoji: '🌫️' },
    { id: '5a-5b-23', word: 'Amends', definition: 'Doing something nice to fix a mistake you made.', category: '5A-5B', exampleSentence: 'He tried to make amends for his error.', imageEmoji: '🛠️' },
    { id: '5a-5b-24', word: 'Curious', definition: 'Wanting to learn and know more.', category: '5A-5B', exampleSentence: 'The curious cat peered inside.', imageEmoji: '🤔' },
    { id: '5a-5b-25', word: 'Reveal', definition: 'To show something that was a secret.', category: '5A-5B', exampleSentence: 'Wait for them to reveal the winner.', imageEmoji: '🎭' },
    { id: '5a-5b-26', word: 'Sentimentality', definition: 'Getting very emotional about old memories.', category: '5A-5B', exampleSentence: 'The song was full of sentimentality.', imageEmoji: '🥺' },
    { id: '5a-5b-27', word: 'Negligent', definition: 'Not taking care of things you are supposed to.', category: '5A-5B', exampleSentence: 'The negligent owner ignored the leak.', imageEmoji: '🏚️' },
    { id: '5a-5b-28', word: 'Baffled', definition: 'Totally and completely confused.', category: '5A-5B', exampleSentence: 'The puzzle completely baffled me.', imageEmoji: '🤷' },
    { id: '5a-5b-29', word: 'Reproachful', definition: 'Giving someone a look that says "I\'m disappointed in you."', category: '5A-5B', exampleSentence: 'She gave him a reproachful glance.', imageEmoji: '😠' },
    { id: '5a-5b-30', word: 'Explore', definition: 'To travel to a new place to learn about it.', category: '5A-5B', exampleSentence: 'Let\'s explore the forest.', imageEmoji: '🧭' },
    { id: '5a-5b-31', word: 'Invincible', definition: 'Too strong to be defeated.', category: '5A-5B', exampleSentence: 'The hero felt invincible.', imageEmoji: '🦸' },
    { id: '5a-5b-32', word: 'Petrified', definition: 'So scared you\'ve turned "to stone."', category: '5A-5B', exampleSentence: 'He was petrified of the ghost.', imageEmoji: '🗿' },
    { id: '5a-5b-33', word: 'Dreaded', definition: 'Something you are really NOT looking forward to.', category: '5A-5B', exampleSentence: 'I dreaded the dentist appointment.', imageEmoji: '😨' },
    { id: '5a-5b-34', word: 'Strained', definition: 'Stretched too thin or worked too hard.', category: '5A-5B', exampleSentence: 'He strained a muscle lifting weights.', imageEmoji: '😫' },
    { id: '5a-5b-35', word: 'Gleaming', definition: 'Shining very brightly.', category: '5A-5B', exampleSentence: 'The gleaming sword captured the light.', imageEmoji: '✨' },
    { id: '5a-5b-36', word: 'Swerve', definition: 'A sudden turn to avoid hitting something.', category: '5A-5B', exampleSentence: 'The car had to swerve to miss the deer.', imageEmoji: '🚗' },
    { id: '5a-5b-37', word: 'Regained', definition: 'Got something back that you lost.', category: '5A-5B', exampleSentence: 'He finally regained his strength.', imageEmoji: '💪' },
    { id: '5a-5b-38', word: 'Ferocious', definition: 'Very fierce and violent.', category: '5A-5B', exampleSentence: 'The ferocious lion roared loudly.', imageEmoji: '🦁' },
    { id: '5a-5b-39', word: 'Excursions', definition: 'Fun, short trips.', category: '5A-5B', exampleSentence: 'We went on several excursions.', imageEmoji: '🚌' },
    { id: '5a-5b-40', word: 'Bountiful', definition: 'Having a lot of something (like a big harvest).', category: '5A-5B', exampleSentence: 'A bountiful harvest of apples.', imageEmoji: '🍎' },
    { id: '5a-5b-41', word: 'Contracted', definition: 'Got smaller or shorter.', category: '5A-5B', exampleSentence: 'The muscle contracted forcefully.', imageEmoji: '📉' },
    { id: '5a-5b-42', word: 'Descendants', definition: 'Your children, grandchildren, and so on.', category: '5A-5B', exampleSentence: 'We are descendants of immigrants.', imageEmoji: '👪' },
    { id: '5a-5b-43', word: 'Inevitable', definition: 'Something that is definitely going to happen.', category: '5A-5B', exampleSentence: 'Change is inevitable.', imageEmoji: '⏳' },
    { id: '5a-5b-44', word: 'Refuge', definition: 'A safe place to hide or stay.', category: '5A-5B', exampleSentence: 'They sought refuge from the storm.', imageEmoji: '⛺' },
    { id: '5a-5b-45', word: 'Indigenous', definition: 'People or plants that have always lived in a place.', category: '5A-5B', exampleSentence: 'Indigenous plants grow best here.', imageEmoji: '🌿' },
    { id: '5a-5b-46', word: 'Surrender', definition: 'To give up and stop fighting.', category: '5A-5B', exampleSentence: 'The army had to surrender.', imageEmoji: '🏳️' },
    { id: '5a-5b-47', word: 'Decimated', definition: 'Destroyed a huge part of a group or place.', category: '5A-5B', exampleSentence: 'The fire decimated the forest.', imageEmoji: '🔥' },
    { id: '5a-5b-48', word: 'Wisdom', definition: 'Knowing what is right because of experience.', category: '5A-5B', exampleSentence: 'Listen to the wisdom of elders.', imageEmoji: '🦉' },
    { id: '5a-5b-49', word: 'Swindled', definition: 'Tricked into giving away your money.', category: '5A-5B', exampleSentence: 'He was swindled out of his savings.', imageEmoji: '👺' },
    { id: '5a-5b-50', word: 'Obscurity', definition: 'Being unknown or "hidden."', category: '5A-5B', exampleSentence: 'The actor rose from obscurity to fame.', imageEmoji: '🌑' },
    { id: '5a-5b-51', word: 'Unsuspecting', definition: 'Not knowing that something is about to happen.', category: '5A-5B', exampleSentence: 'The unsuspecting victim walked into the trap.', imageEmoji: '😯' },
    { id: '5a-5b-52', word: 'Assassinated', definition: 'Killed for a political reason.', category: '5A-5B', exampleSentence: 'The leader was assassinated.', imageEmoji: '🔫' },
    { id: '5a-5b-53', word: 'Dedicated', definition: 'Giving all your time and effort to one thing.', category: '5A-5B', exampleSentence: 'She is a dedicated doctor.', imageEmoji: '🎯' },
    { id: '5a-5b-54', word: 'Inherited', definition: 'Getting something from your parents or grandparents.', category: '5A-5B', exampleSentence: 'He inherited his father\'s eyes.', imageEmoji: '🧬' },
    { id: '5a-5b-55', word: 'Innovative', definition: 'Coming up with cool, new ideas.', category: '5A-5B', exampleSentence: 'An innovative way to solve the problem.', imageEmoji: '💡' },
    { id: '5a-5b-56', word: 'Resented', definition: 'Being mad at someone because things seem unfair.', category: '5A-5B', exampleSentence: 'She resented being told what to do.', imageEmoji: '😡' },
    { id: '5a-5b-57', word: 'Resourceful', definition: 'Being good at solving problems with what you have.', category: '5A-5B', exampleSentence: 'A resourceful scout can find water.', imageEmoji: '🛠️' },
    { id: '5a-5b-58', word: 'Razed', definition: 'Completely tore down a building.', category: '5A-5B', exampleSentence: 'The old factory was razed.', imageEmoji: '🚜' },
    { id: '5a-5b-59', word: 'Perplexing', definition: 'Very, very confusing.', category: '5A-5B', exampleSentence: 'The mystery was quite perplexing.', imageEmoji: '😵‍💫' },
    { id: '5a-5b-60', word: 'Status', definition: 'Your rank or how people see you in a group.', category: '5A-5B', exampleSentence: 'He has high status in the company.', imageEmoji: '📊' },
    { id: '5a-5b-61', word: 'Privilege', definition: 'A special "extra" right that not everyone has.', category: '5A-5B', exampleSentence: 'Education is a privilege.', imageEmoji: '🎟️' },
    { id: '5a-5b-62', word: 'Rejected', definition: 'Turned down or told "no."', category: '5A-5B', exampleSentence: 'My application was rejected.', imageEmoji: '❌' },
    { id: '5a-5b-63', word: 'Cramped', definition: 'A space that is too small to move in.', category: '5A-5B', exampleSentence: 'We sat in a cramped little room.', imageEmoji: '📦' },
    { id: '5a-5b-64', word: 'Absolute', definition: '100% total or complete.', category: '5A-5B', exampleSentence: 'I have absolute faith in you.', imageEmoji: '💯' },
    { id: '5a-5b-65', word: 'Renowned', definition: 'Famous for being excellent at something.', category: '5A-5B', exampleSentence: 'She is a renowned scientist.', imageEmoji: '🌟' },
    { id: '5a-5b-66', word: 'Considerable', definition: 'A pretty large amount.', category: '5A-5B', exampleSentence: 'It took a considerable amount of time.', imageEmoji: '📈' },
    { id: '5a-5b-67', word: 'Deformed', definition: 'Not shaped correctly.', category: '5A-5B', exampleSentence: 'The tree grew deformed.', imageEmoji: '🥨' },
    { id: '5a-5b-68', word: 'Susceptible', definition: 'Likely to get sick or be influenced by others.', category: '5A-5B', exampleSentence: 'Babies are susceptible to colds.', imageEmoji: '🤒' },
    { id: '5a-5b-69', word: 'Barbaric', definition: 'Cruel and uncivilized.', category: '5A-5B', exampleSentence: 'Those were barbaric times.', imageEmoji: '🦴' },
    { id: '5a-5b-70', word: 'Dynasty', definition: 'A powerful family that rules for a long time.', category: '5A-5B', exampleSentence: 'The Ming Dynasty ruled China.', imageEmoji: '🏯' },
    { id: '5a-5b-71', word: 'Astounded', definition: 'Totally shocked or amazed.', category: '5A-5B', exampleSentence: 'We were astounded by the magic trick.', imageEmoji: '😲' },
    { id: '5a-5b-72', word: 'Captivated', definition: 'So interested that you can\'t look away.', category: '5A-5B', exampleSentence: 'The movie captivated the audience.', imageEmoji: '🤩' },
    { id: '5a-5b-73', word: 'Prosperous', definition: 'Being rich and successful.', category: '5A-5B', exampleSentence: 'The business is very prosperous.', imageEmoji: '💰' },
    { id: '5a-5b-74', word: 'Heir', definition: 'The person who gets the money/title when someone dies.', category: '5A-5B', exampleSentence: 'He is the heir to the throne.', imageEmoji: '👑' },
    { id: '5a-5b-75', word: 'Resisted', definition: 'Fought against something or said no.', category: '5A-5B', exampleSentence: 'She resisted the temptation.', imageEmoji: '✋' },
    { id: '5a-5b-76', word: 'Opulence', definition: 'Having tons of fancy, expensive things.', category: '5A-5B', exampleSentence: 'The palace was filled with opulence.', imageEmoji: '🏰' },
    { id: '5a-5b-77', word: 'Conflict', definition: 'A big disagreement or fight.', category: '5A-5B', exampleSentence: 'We want to avoid conflict.', imageEmoji: '⚔️' },
    { id: '5a-5b-78', word: 'Pompous', definition: 'Acting like you are way more important than you are.', category: '5A-5B', exampleSentence: 'He gave a pompous speech.', imageEmoji: '😤' },
    { id: '5a-5b-79', word: 'Retreated', definition: 'Turned around and ran away from a fight.', category: '5A-5B', exampleSentence: 'The enemy retreated quickly.', imageEmoji: '🏃' },
    { id: '5a-5b-80', word: 'Conspire', definition: 'To plan something secret (and usually bad) together.', category: '5A-5B', exampleSentence: 'Villains often conspire together.', imageEmoji: '🕵️' },
    { id: '5a-5b-81', word: 'Descend', definition: 'To go down (like walking down stairs).', category: '5A-5B', exampleSentence: 'Carefully descend the ladder.', imageEmoji: '🪜' },
    { id: '5a-5b-82', word: 'Aristocratic', definition: 'Coming from a very rich and fancy family.', category: '5A-5B', exampleSentence: 'She has an aristocratic manner.', imageEmoji: '🎩' },
    { id: '5a-5b-83', word: 'Endeavor', definition: 'To try really hard at something.', category: '5A-5B', exampleSentence: 'Good luck with your new endeavor.', imageEmoji: '🚀' },
    { id: '5a-5b-84', word: 'Defied', definition: 'Refused to follow an order.', category: '5A-5B', exampleSentence: 'He defied his parents\' rules.', imageEmoji: '🚫' },
    { id: '5a-5b-85', word: 'Debate', definition: 'A formal argument about two different ideas.', category: '5A-5B', exampleSentence: 'We held a class debate.', imageEmoji: '🗣️' },
    { id: '5a-5b-86', word: 'Notorious', definition: 'Famous for doing something bad.', category: '5A-5B', exampleSentence: 'A notorious pirate sailed here.', imageEmoji: '🏴‍☠️' },
    { id: '5a-5b-87', word: 'Released', definition: 'Let go or set free.', category: '5A-5B', exampleSentence: 'The bird was released into the wild.', imageEmoji: '🕊️' },
    { id: '5a-5b-88', word: 'Tyranny', definition: 'When a leader is mean and unfair.', category: '5A-5B', exampleSentence: 'People fought against tyranny.', imageEmoji: '✊' },
    { id: '5a-5b-89', word: 'Eulogy', definition: 'A speech given at a funeral to remember someone.', category: '5A-5B', exampleSentence: 'He gave a touching eulogy.', imageEmoji: '📜' },
    { id: '5a-5b-90', word: 'Unreliable', definition: 'Someone you can\'t count on to do what they say.', category: '5A-5B', exampleSentence: 'The old car is unreliable.', imageEmoji: '🛠️' },
    { id: '5a-5b-91', word: 'Inspired', definition: 'Feeling like you want to do something great.', category: '5A-5B', exampleSentence: 'The art inspired me to paint.', imageEmoji: '🎨' },
    { id: '5a-5b-92', word: 'Anxiety', definition: 'A nervous, worried feeling.', category: '5A-5B', exampleSentence: 'Tests can cause anxiety.', imageEmoji: '😰' },
    { id: '5a-5b-93', word: 'Precautions', definition: 'Things you do to stay safe before an accident happens.', category: '5A-5B', exampleSentence: 'Take precautions when hiking.', imageEmoji: '⚠️' },
    { id: '5a-5b-94', word: 'Amiss', definition: 'When something feels "off" or wrong.', category: '5A-5B', exampleSentence: 'I sensed something was amiss.', imageEmoji: '🤨' },
    { id: '5a-5b-95', word: 'Courteously', definition: 'Being very polite and kind.', category: '5A-5B', exampleSentence: 'He greeted us courteously.', imageEmoji: '🎩' },
    { id: '5a-5b-96', word: 'Audacity', definition: 'Being so bold that it’s almost rude.', category: '5A-5B', exampleSentence: 'She had the audacity to lie.', imageEmoji: '😠' },
    { id: '5a-5b-97', word: 'Convinced', definition: 'Completely sure that something is true.', category: '5A-5B', exampleSentence: 'I am convinced he is right.', imageEmoji: '👍' },
    { id: '5a-5b-98', word: 'Incessantly', definition: 'Without ever stopping.', category: '5A-5B', exampleSentence: 'The dog barked incessantly.', imageEmoji: '🐕' },
    { id: '5a-5b-99', word: 'Agony', definition: 'A lot of physical or mental pain.', category: '5A-5B', exampleSentence: 'The injury caused great agony.', imageEmoji: '😫' },
    { id: '5a-5b-100', word: 'Glory', definition: 'Being famous and praised by everyone.', category: '5A-5B', exampleSentence: 'They fought for honor and glory.', imageEmoji: '🏆' },
    { id: '5a-5b-101', word: 'Conquered', definition: 'Took over a place by force.', category: '5A-5B', exampleSentence: 'They conquered the castle.', imageEmoji: '🏰' },
    { id: '5a-5b-102', word: 'Revolt', definition: 'A big fight against the people in charge.', category: '5A-5B', exampleSentence: 'The peasants started a revolt.', imageEmoji: '📢' },
    { id: '5a-5b-103', word: 'Condemned', definition: 'Given a strong punishment.', category: '5A-5B', exampleSentence: 'The building was condemned.', imageEmoji: '🏚️' },
    { id: '5a-5b-104', word: 'Bloodthirsty', definition: 'Eager to fight or be violent.', category: '5A-5B', exampleSentence: 'A bloodthirsty warrior appeared.', imageEmoji: '🗡️' },
    { id: '5a-5b-105', word: 'Disband', definition: 'To break up a group so they go their separate ways.', category: '5A-5B', exampleSentence: 'The band decided to disband.', imageEmoji: '💔' },
    { id: '5a-5b-106', word: 'Triumphant', definition: 'Feeling great because you won!', category: '5A-5B', exampleSentence: 'The triumphant winner smiled.', imageEmoji: '🥂' },
    { id: '5a-5b-107', word: 'Doomed', definition: 'No chance of winning; sure to fail.', category: '5A-5B', exampleSentence: 'The plan was doomed from the start.', imageEmoji: '💀' },
    { id: '5a-5b-108', word: 'Crucial', definition: 'Something you absolutely must have.', category: '5A-5B', exampleSentence: 'Water is crucial for life.', imageEmoji: '💧' },
    { id: '5a-5b-109', word: 'Ambitious', definition: 'Having big goals and working hard to reach them.', category: '5A-5B', exampleSentence: 'She is an ambitious student.', imageEmoji: '🧗' },
    { id: '5a-5b-110', word: 'Vision', definition: 'A dream or goal for the future.', category: '5A-5B', exampleSentence: 'He had a vision of world peace.', imageEmoji: '👁️' },
    { id: '5a-5b-111', word: 'Significant', definition: 'Very important or a big deal.', category: '5A-5B', exampleSentence: 'This is a significant discovery.', imageEmoji: '‼️' },
    { id: '5a-5b-112', word: 'Intrigued', definition: 'Very curious and interested.', category: '5A-5B', exampleSentence: 'The mystery intrigued me.', imageEmoji: '🕵️' },
    { id: '5a-5b-113', word: 'Acquired', definition: 'Got something new.', category: '5A-5B', exampleSentence: 'I acquired a new skill.', imageEmoji: '🎁' },
    { id: '5a-5b-114', word: 'Accumulated', definition: 'Collected a pile of things over time.', category: '5A-5B', exampleSentence: 'Dust accumulated on the shelf.', imageEmoji: '📚' },
    { id: '5a-5b-115', word: 'Elaborate', definition: 'Having a lot of tiny, fancy details.', category: '5A-5B', exampleSentence: 'The costume was very elaborate.', imageEmoji: '👗' },
    { id: '5a-5b-116', word: 'Cumbersome', definition: 'Large, heavy, and hard to move.', category: '5A-5B', exampleSentence: 'The box was cumbersome to carry.', imageEmoji: '📦' },
    { id: '5a-5b-117', word: 'Painstaking', definition: 'Doing something very slowly and carefully.', category: '5A-5B', exampleSentence: 'It took painstaking work to fix.', imageEmoji: '🧐' },
    { id: '5a-5b-118', word: 'Nagged', definition: 'Bothered someone over and over to do something.', category: '5A-5B', exampleSentence: 'My mom nagged me to clean up.', imageEmoji: '🗣️' },
    { id: '5a-5b-119', word: 'Expose', definition: 'To show something that was hidden.', category: '5A-5B', exampleSentence: 'The sun will expose the truth.', imageEmoji: '☀️' },
    { id: '5a-5b-120', word: 'Illogical', definition: 'Doesn\'t make any sense at all.', category: '5A-5B', exampleSentence: 'His fear of cats is illogical.', imageEmoji: '🚫' },
    { id: '5a-5b-121', word: 'Disciples', definition: 'Students who follow a leader.', category: '5A-5B', exampleSentence: 'The teacher had many disciples.', imageEmoji: '🙏' },
    { id: '5a-5b-122', word: 'Offended', definition: 'Feeling hurt because someone was rude.', category: '5A-5B', exampleSentence: 'She was offended by the joke.', imageEmoji: '😤' },
    { id: '5a-5b-123', word: 'Scorned', definition: 'Looked down on or treated like they weren\'t important.', category: '5A-5B', exampleSentence: 'He scorned the cheap gift.', imageEmoji: '😒' },
    { id: '5a-5b-124', word: 'Suppress', definition: 'To hold something down or stop it from growing.', category: '5A-5B', exampleSentence: 'Try to suppress your cough.', imageEmoji: '🙊' },
    { id: '5a-5b-125', word: 'Rebel', definition: 'To go against the people in charge.', category: '5A-5B', exampleSentence: 'Teenagers often rebel.', imageEmoji: '🤟' },
    { id: '5a-5b-126', word: 'Accused', definition: 'Blamed for doing something wrong.', category: '5A-5B', exampleSentence: 'He was accused of stealing.', imageEmoji: '👉' },
    { id: '5a-5b-127', word: 'Eloquently', definition: 'Speaking in a beautiful, smart way.', category: '5A-5B', exampleSentence: 'She spoke eloquently about peace.', imageEmoji: '🎻' },
    { id: '5a-5b-128', word: 'Interfered', definition: 'Got in the middle of something that wasn\'t your business.', category: '5A-5B', exampleSentence: 'Don\'t let work interfere with fun.', imageEmoji: '🛑' },
    { id: '5a-5b-129', word: 'Perilous', definition: 'Extremely dangerous.', category: '5A-5B', exampleSentence: 'The heavy traffic was perilous.', imageEmoji: '⚠️' },
    { id: '5a-5b-130', word: 'Inhabited', definition: 'Lived in a place.', category: '5A-5B', exampleSentence: 'Owls inhabited the old barn.', imageEmoji: '🦉' },
    { id: '5a-5b-131', word: 'Devised', definition: 'Invented a smart way to do something.', category: '5A-5B', exampleSentence: 'They devised a clever plan.', imageEmoji: '📝' },
    { id: '5a-5b-132', word: 'Conceal', definition: 'To hide something so nobody sees it.', category: '5A-5B', exampleSentence: 'He tried to conceal his smile.', imageEmoji: '🙈' },
    { id: '5a-5b-133', word: 'Devoured', definition: 'Ate every single bite super fast.', category: '5A-5B', exampleSentence: 'The wolf devoured the meal.', imageEmoji: '🐺' },
    { id: '5a-5b-134', word: 'Spree', definition: 'Doing a lot of one thing all at once (like a shopping spree).', category: '5A-5B', exampleSentence: 'She went on a shopping spree.', imageEmoji: '🛍️' },
    { id: '5a-5b-135', word: 'Comrades', definition: 'Good friends or partners.', category: '5A-5B', exampleSentence: 'Soldiers rely on their comrades.', imageEmoji: '🤝' },
    { id: '5a-5b-136', word: 'Desired', definition: 'Wanted something very, very much.', category: '5A-5B', exampleSentence: 'He desired a fast car.', imageEmoji: '🏎️' },
    { id: '5a-5b-137', word: 'Daze', definition: 'Feeling confused or "spaced out."', category: '5A-5B', exampleSentence: 'He walked around in a daze.', imageEmoji: '🌀' },
    { id: '5a-5b-138', word: 'Collapsed', definition: 'Fell down or broke apart suddenly.', category: '5A-5B', exampleSentence: 'The old chair collapsed.', imageEmoji: '🪑' },
    { id: '5a-5b-139', word: 'Equivalent', definition: 'The exact same as something else.', category: '5A-5B', exampleSentence: 'Ten dimes are equivalent to a dollar.', imageEmoji: '⚖️' },
    { id: '5a-5b-140', word: 'Jealousy', definition: 'Wanting what someone else has.', category: '5A-5B', exampleSentence: 'Jealousy can ruin friendships.', imageEmoji: '😒' },
    { id: '5a-5b-141', word: 'Seized', definition: 'Snatched or grabbed quickly.', category: '5A-5B', exampleSentence: 'He seized the opportunity.', imageEmoji: '🤏' },
    { id: '5a-5b-142', word: 'Insane', definition: 'Totally wild or "crazy."', category: '5A-5B', exampleSentence: 'That rollercoaster is insane!', imageEmoji: '🎢' },
    { id: '5a-5b-143', word: 'Plotted', definition: 'Made a secret plan.', category: '5A-5B', exampleSentence: 'They plotted a surprise party.', imageEmoji: '🗺️' },
    { id: '5a-5b-144', word: 'Persuaded', definition: 'Talked someone into doing something.', category: '5A-5B', exampleSentence: 'I persuaded him to go.', imageEmoji: '🗣️' },
    { id: '5a-5b-145', word: 'Pierce', definition: 'To poke a hole through something sharp.', category: '5A-5B', exampleSentence: 'The needle can pierce fabric.', imageEmoji: '🪡' },
    { id: '5a-5b-146', word: 'Savage', definition: 'Wild and fierce.', category: '5A-5B', exampleSentence: 'A savage storm hit the coast.', imageEmoji: '🌪️' },
    { id: '5a-5b-147', word: 'Vicious', definition: 'Mean and scary.', category: '5A-5B', exampleSentence: 'Beware of the vicious dog.', imageEmoji: '🐕' },
    { id: '5a-5b-148', word: 'Chaotic', definition: 'Totally messy and out of control.', category: '5A-5B', exampleSentence: 'The traffic was chaotic.', imageEmoji: '🚦' },
    { id: '5a-5b-149', word: 'Mercy', definition: 'Choosing to be kind instead of punishing someone.', category: '5A-5B', exampleSentence: 'The king showed mercy.', imageEmoji: '🙏' },
    { id: '5a-5b-150', word: 'Insatiable', definition: 'A hunger or want that never goes away.', category: '5A-5B', exampleSentence: 'He has an insatiable appetite.', imageEmoji: '🍔' },
    { id: '5a-5b-151', word: 'Deceive', definition: 'To trick someone or tell a lie.', category: '5A-5B', exampleSentence: 'Do not try to deceive me.', imageEmoji: '🤥' },
    { id: '5a-5b-152', word: 'Summoned', definition: 'Ordered to come over right away.', category: '5A-5B', exampleSentence: 'The principal summoned him.', imageEmoji: '📢' },
    { id: '5a-5b-153', word: 'Resume', definition: 'To start again after a break.', category: '5A-5B', exampleSentence: 'We will resume the game later.', imageEmoji: '▶️' },
    { id: '5a-5b-154', word: 'Voraciously', definition: 'Eating like you are a starving animal.', category: '5A-5B', exampleSentence: 'He read books voraciously.', imageEmoji: '📚' },
    { id: '5a-5b-155', word: 'Intoxicated', definition: 'Acting dizzy or "drunk."', category: '5A-5B', exampleSentence: 'He was intoxicated by the fumes.', imageEmoji: '🥴' },
    { id: '5a-5b-156', word: 'Auspicious', definition: 'A sign that good luck is coming.', category: '5A-5B', exampleSentence: 'Red is an auspicious color.', imageEmoji: '🧧' },
    { id: '5a-5b-157', word: 'Gratitude', definition: 'Saying a big "thank you."', category: '5A-5B', exampleSentence: 'She expressed deep gratitude.', imageEmoji: '🙌' },
    { id: '5a-5b-158', word: 'Abhorred', definition: 'Really, really hated.', category: '5A-5B', exampleSentence: 'He abhorred violence.', imageEmoji: '🚫' },
    { id: '5a-5b-159', word: 'Sacred', definition: 'Very special or holy.', category: '5A-5B', exampleSentence: 'The temple is a sacred place.', imageEmoji: '🕍' },
    { id: '5a-5b-160', word: 'Tempted', definition: 'Really wanting to do something you probably shouldn\'t.', category: '5A-5B', exampleSentence: 'I was tempted to eat the cake.', imageEmoji: '🍰' },
    { id: '5a-5b-161', word: 'Blessed', definition: 'Having very good luck or being thankful.', category: '5A-5B', exampleSentence: 'We felt truly blessed.', imageEmoji: '✨' },
    { id: '5a-5b-162', word: 'Precious', definition: 'Something that is worth a lot or very dear to you.', category: '5A-5B', exampleSentence: 'Her ring is very precious.', imageEmoji: '💍' },
    { id: '5a-5b-163', word: 'Slaughter', definition: 'To kill in a violent way.', category: '5A-5B', exampleSentence: 'The battle ended in slaughter.', imageEmoji: '⚔️' },
    { id: '5a-5b-164', word: 'Fret', definition: 'To worry or be nervous.', category: '5A-5B', exampleSentence: 'Don\'t fret about the test.', imageEmoji: '😟' },
    { id: '5a-5b-165', word: 'Sorrow', definition: 'A very deep sadness.', category: '5A-5B', exampleSentence: 'He felt great sorrow.', imageEmoji: '😢' },
    { id: '5a-5b-166', word: 'Willingness', definition: 'Being ready and happy to help.', category: '5A-5B', exampleSentence: 'He showed willingness to learn.', imageEmoji: '🙋' },
    { id: '5a-5b-167', word: 'Abolished', definition: 'Ended something officially (like a bad rule).', category: '5A-5B', exampleSentence: 'Slavery was abolished.', imageEmoji: '📜' },
    { id: '5a-5b-168', word: 'Despondent', definition: 'Feeling like there is zero hope left.', category: '5A-5B', exampleSentence: 'She felt despondent after failing.', imageEmoji: '😞' },
    { id: '5a-5b-169', word: 'Dilapidated', definition: 'Run-down and falling apart.', category: '5A-5B', exampleSentence: 'They fixed up the dilapidated house.', imageEmoji: '🏚️' }
];
