import { VocabularyWord } from "./types";

export const KA_5A_WORDS: VocabularyWord[] = [
    { id: "ka5a-1", word: "Precisely", definition: "Exactly", pronunciation: "/.../", imageEmoji: "🎯", exampleSentence: "The clock struck precisely at noon.", category: "KA-5A" },
    { id: "ka5a-2", word: "Sumptuous", definition: "Very fancy and expensive (a sumptuous meal)", pronunciation: "/.../", imageEmoji: "🍱", exampleSentence: "We enjoyed a sumptuous feast.", category: "KA-5A" },
    { id: "ka5a-3", word: "Luxurious", definition: "Very fancy and comfortable", pronunciation: "/.../", imageEmoji: "🛋️", exampleSentence: "The hotel room was luxurious.", category: "KA-5A" },
    { id: "ka5a-4", word: "Plump", definition: "A little fat", pronunciation: "/.../", imageEmoji: "🍑", exampleSentence: "The baby had plump cheeks.", category: "KA-5A" },
    { id: "ka5a-5", word: "Wretched", definition: "Very unhappy", pronunciation: "/.../", imageEmoji: "😫", exampleSentence: "He felt wretched after the mistake.", category: "KA-5A" },
    { id: "ka5a-6", word: "Anxious", definition: "Worried or nervous", pronunciation: "/.../", imageEmoji: "😰", exampleSentence: "She was anxious about the test.", category: "KA-5A" },
    { id: "ka5a-7", word: "Blurt", definition: "Say something suddenly without thinking", pronunciation: "/.../", imageEmoji: "🗣️", exampleSentence: "He tended to blurt out the answer.", category: "KA-5A" },
    { id: "ka5a-8", word: "Startled", definition: "Suddenly surprised", pronunciation: "/.../", imageEmoji: "😲", exampleSentence: "The loud noise startled me.", category: "KA-5A" },
    { id: "ka5a-9", word: "Hesitate", definition: "Stop because you are unsure", pronunciation: "/.../", imageEmoji: "🤔", exampleSentence: "Don't hesitate to ask for help.", category: "KA-5A" },
    { id: "ka5a-10", word: "Content", definition: "Happy and satisfied", pronunciation: "/.../", imageEmoji: "😌", exampleSentence: "He was content with his life.", category: "KA-5A" },
    { id: "ka5a-11", word: "Earnestly", definition: "In a serious and honest way", pronunciation: "/.../", imageEmoji: "🙏", exampleSentence: "She spoke earnestly about her goals.", category: "KA-5A" },
    { id: "ka5a-12", word: "Altruistic", definition: "Caring about others more than yourself", pronunciation: "/.../", imageEmoji: "🤲", exampleSentence: "His altruistic nature helped many people.", category: "KA-5A" },
    { id: "ka5a-13", word: "Temperamental", definition: "Moody; feelings change fast", pronunciation: "/.../", imageEmoji: "🎭", exampleSentence: "The actor was known for being temperamental.", category: "KA-5A" },
    { id: "ka5a-14", word: "Unjust", definition: "Unfair", pronunciation: "/.../", imageEmoji: "⚖️", exampleSentence: "The punishment seemed unjust.", category: "KA-5A" },
    { id: "ka5a-15", word: "Loathed", definition: "Hated very much", pronunciation: "/.../", imageEmoji: "😠", exampleSentence: "He loathed broccoli since childhood.", category: "KA-5A" },
    { id: "ka5a-16", word: "Proposal", definition: "A suggestion or plan", pronunciation: "/.../", imageEmoji: "📋", exampleSentence: "She agreed to the proposal.", category: "KA-5A" },
    { id: "ka5a-17", word: "Grim", definition: "Dark, sad, or scary", pronunciation: "/.../", imageEmoji: "🌑", exampleSentence: "The future looked grim.", category: "KA-5A" },
    { id: "ka5a-18", word: "Fierce", definition: "Very strong or angry", pronunciation: "/.../", imageEmoji: "🐯", exampleSentence: "The lion gave a fierce roar.", category: "KA-5A" },
    { id: "ka5a-19", word: "Bewilderment", definition: "Feeling very confused", pronunciation: "/.../", imageEmoji: "😵‍💫", exampleSentence: "He stared in bewilderment.", category: "KA-5A" },
    { id: "ka5a-20", word: "Imbeciles", definition: "Foolish people (a rude word)", pronunciation: "/.../", imageEmoji: "🤪", exampleSentence: "He muttered about imbeciles under his breath.", category: "KA-5A" },
    { id: "ka5a-21", word: "Appalled", definition: "Very shocked", pronunciation: "/.../", imageEmoji: "😱", exampleSentence: "She was appalled by the mess.", category: "KA-5A" },
    { id: "ka5a-22", word: "Preposterous", definition: "Very silly or ridiculous", pronunciation: "/.../", imageEmoji: "🤡", exampleSentence: "That is a preposterous idea!", category: "KA-5A" },
    { id: "ka5a-23", word: "Compliment", definition: "Say something nice about someone", pronunciation: "/.../", imageEmoji: "💬", exampleSentence: "He gave her a nice compliment.", category: "KA-5A" },
    { id: "ka5a-24", word: "Sage", definition: "A wise person", pronunciation: "/.../", imageEmoji: "🧙‍♂️", exampleSentence: "The sage gave good advice.", category: "KA-5A" },
    { id: "ka5a-25", word: "Distress", definition: "Great pain or sadness", pronunciation: "/.../", imageEmoji: "😫", exampleSentence: "The news caused her great distress.", category: "KA-5A" },
    { id: "ka5a-26", word: "Recite", definition: "Say something from memory", pronunciation: "/.../", imageEmoji: "🗣️", exampleSentence: "He can recite the poem by heart.", category: "KA-5A" },
    { id: "ka5a-27", word: "Logical", definition: "Making sense", pronunciation: "/.../", imageEmoji: "🧠", exampleSentence: "That is a logical conclusion.", category: "KA-5A" },
    { id: "ka5a-28", word: "Distinguished", definition: "Important or respected", pronunciation: "/.../", imageEmoji: "🎩", exampleSentence: "He had a distinguished career.", category: "KA-5A" },
    { id: "ka5a-29", word: "Cunning", definition: "Clever in a sneaky way", pronunciation: "/.../", imageEmoji: "🦊", exampleSentence: "The fox was very cunning.", category: "KA-5A" },
    { id: "ka5a-30", word: "Mischief", definition: "Playful bad behavior", pronunciation: "/.../", imageEmoji: "😈", exampleSentence: "The puppy got into some mischief.", category: "KA-5A" },
    { id: "ka5a-31", word: "Pity", definition: "Feeling sorry for someone", pronunciation: "/.../", imageEmoji: "🥺", exampleSentence: "She felt pity for the lost dog.", category: "KA-5A" },
    { id: "ka5a-32", word: "Verdict", definition: "Final decision or result", pronunciation: "/.../", imageEmoji: "🔨", exampleSentence: "The jury reached a verdict.", category: "KA-5A" },
    { id: "ka5a-33", word: "Prosecutor", definition: "Lawyer who says someone did a crime", pronunciation: "/.../", imageEmoji: "⚖️", exampleSentence: "The prosecutor presented the evidence.", category: "KA-5A" },
    { id: "ka5a-34", word: "Perpetrator", definition: "Person who did a bad act", pronunciation: "/.../", imageEmoji: "🕵️", exampleSentence: "The perpetrator was caught.", category: "KA-5A" },
    { id: "ka5a-35", word: "Succinctly", definition: "In a short and clear way", pronunciation: "/.../", imageEmoji: "📏", exampleSentence: "He explained the plan succinctly.", category: "KA-5A" },
    { id: "ka5a-36", word: "Scarcely", definition: "Almost not at all", pronunciation: "/.../", imageEmoji: "🤏", exampleSentence: "There was scarcely any food left.", category: "KA-5A" },
    { id: "ka5a-37", word: "Conceited", definition: "Too proud of yourself", pronunciation: "/.../", imageEmoji: "🪞", exampleSentence: "He was too conceited to listen.", category: "KA-5A" },
    { id: "ka5a-38", word: "Humiliated", definition: "Very embarrassed", pronunciation: "/.../", imageEmoji: "😳", exampleSentence: "She felt humiliated by the mistake.", category: "KA-5A" },
    { id: "ka5a-39", word: "Mortified", definition: "Extremely embarrassed", pronunciation: "/.../", imageEmoji: "😫", exampleSentence: "He was mortified when he tripped.", category: "KA-5A" },
    { id: "ka5a-40", word: "Vowed", definition: "Promised strongly", pronunciation: "/.../", imageEmoji: "🤚", exampleSentence: "He vowed to return.", category: "KA-5A" },
    { id: "ka5a-41", word: "Deplorable", definition: "Very bad or shameful", pronunciation: "/.../", imageEmoji: "👎", exampleSentence: "The conditions were deplorable.", category: "KA-5A" },
    { id: "ka5a-42", word: "Scanty", definition: "Very little", pronunciation: "/.../", imageEmoji: "🤏", exampleSentence: "The evidence was scanty.", category: "KA-5A" },
    { id: "ka5a-43", word: "Thrived", definition: "Did very well", pronunciation: "/.../", imageEmoji: "📈", exampleSentence: "The plant thrived in the sun.", category: "KA-5A" },
    { id: "ka5a-44", word: "Folly", definition: "A foolish mistake", pronunciation: "/.../", imageEmoji: "🃏", exampleSentence: "It was folly to ignore the warnings.", category: "KA-5A" },
    { id: "ka5a-45", word: "Jeered", definition: "Laughed at or made fun of", pronunciation: "/.../", imageEmoji: "😆", exampleSentence: "The crowd jeered at the opposing team.", category: "KA-5A" },
    { id: "ka5a-46", word: "Arrogance", definition: "Acting like you are better than others", pronunciation: "/.../", imageEmoji: "😤", exampleSentence: "His arrogance annoyed everyone.", category: "KA-5A" },
    { id: "ka5a-47", word: "Essential", definition: "Very important; needed", pronunciation: "/.../", imageEmoji: "⭐", exampleSentence: "Water is essential for life.", category: "KA-5A" },
    { id: "ka5a-48", word: "Justice", definition: "Fairness", pronunciation: "/.../", imageEmoji: "⚖️", exampleSentence: "We must fight for justice.", category: "KA-5A" },
    { id: "ka5a-49", word: "Committed", definition: "Did (usually a bad act)", pronunciation: "/.../", imageEmoji: "📝", exampleSentence: "He committed a crime.", category: "KA-5A" },
    { id: "ka5a-50", word: "Deserted", definition: "Left behind", pronunciation: "/.../", imageEmoji: "🌵", exampleSentence: "The town was deserted.", category: "KA-5A" },
    { id: "ka5a-51", word: "Reaped", definition: "Collected or gained", pronunciation: "/.../", imageEmoji: "🌾", exampleSentence: "He reaped the rewards of hard work.", category: "KA-5A" },
    { id: "ka5a-52", word: "Miser", definition: "Someone who hates spending money", pronunciation: "/.../", imageEmoji: "💰", exampleSentence: "The old miser saved every penny.", category: "KA-5A" },
    { id: "ka5a-53", word: "Lame", definition: "Hurt and hard to walk", pronunciation: "/.../", imageEmoji: "🦯", exampleSentence: "The horse was lame.", category: "KA-5A" },
    { id: "ka5a-54", word: "Tempting", definition: "Very attractive", pronunciation: "/.../", imageEmoji: "🍰", exampleSentence: "The cake looked tempting.", category: "KA-5A" },
    { id: "ka5a-55", word: "Faithful", definition: "Loyal and dependable", pronunciation: "/.../", imageEmoji: "🐕", exampleSentence: "The dog was a faithful companion.", category: "KA-5A" },
    { id: "ka5a-56", word: "Peril", definition: "Danger", pronunciation: "/.../", imageEmoji: "⚠️", exampleSentence: "They were in great peril.", category: "KA-5A" },
    { id: "ka5a-57", word: "Meantime", definition: "During that time", pronunciation: "/.../", imageEmoji: "⏳", exampleSentence: "In the meantime, we waited.", category: "KA-5A" },
    { id: "ka5a-58", word: "Accustomed", definition: "Used to something", pronunciation: "/.../", imageEmoji: "🔄", exampleSentence: "She was accustomed to hard work.", category: "KA-5A" },
    { id: "ka5a-59", word: "Uproar", definition: "Loud noise and excitement", pronunciation: "/.../", imageEmoji: "📢", exampleSentence: "The announcement caused an uproar.", category: "KA-5A" },
    { id: "ka5a-60", word: "Preoccupied", definition: "Busy thinking about something", pronunciation: "/.../", imageEmoji: "🤔", exampleSentence: "He seemed preoccupied with his thoughts.", category: "KA-5A" },
    { id: "ka5a-61", word: "Vicar", definition: "A church leader", pronunciation: "/.../", imageEmoji: "⛪", exampleSentence: "The vicar gave a sermon.", category: "KA-5A" },
    { id: "ka5a-62", word: "Emerged", definition: "Came out", pronunciation: "/.../", imageEmoji: "🐣", exampleSentence: "The sun emerged from the clouds.", category: "KA-5A" },
    { id: "ka5a-63", word: "Daft", definition: "Silly or foolish", pronunciation: "/.../", imageEmoji: "🤪", exampleSentence: "Don't be daft.", category: "KA-5A" },
    { id: "ka5a-64", word: "Frantically", definition: "In a wild, panicked way", pronunciation: "/.../", imageEmoji: "🏃", exampleSentence: "She searched frantically for her keys.", category: "KA-5A" },
    { id: "ka5a-65", word: "Commotion", definition: "Loud noise and confusion", pronunciation: "/.../", imageEmoji: "💥", exampleSentence: "There was a commotion in the hall.", category: "KA-5A" },
    { id: "ka5a-66", word: "Pry", definition: "Force something open", pronunciation: "/.../", imageEmoji: "⛏️", exampleSentence: "He tried to pry the box open.", category: "KA-5A" },
    { id: "ka5a-67", word: "Mourned", definition: "Felt sad and cried over loss", pronunciation: "/.../", imageEmoji: "😢", exampleSentence: "They mourned the loss of their friend.", category: "KA-5A" },
    { id: "ka5a-68", word: "Consolation", definition: "Comfort after sadness", pronunciation: "/.../", imageEmoji: "🫂", exampleSentence: "Winning second place was small consolation.", category: "KA-5A" },
    { id: "ka5a-69", word: "Luxuriant", definition: "Thick and healthy (plants, hair)", pronunciation: "/.../", imageEmoji: "🌿", exampleSentence: "The garden was luxuriant.", category: "KA-5A" },
    { id: "ka5a-70", word: "Elated", definition: "Very happy", pronunciation: "/.../", imageEmoji: "🤩", exampleSentence: "She was elated by the news.", category: "KA-5A" },
    { id: "ka5a-71", word: "Ponder", definition: "Think deeply", pronunciation: "/.../", imageEmoji: "💭", exampleSentence: "He paused to ponder the question.", category: "KA-5A" },
    { id: "ka5a-72", word: "Toiled", definition: "Worked very hard", pronunciation: "/.../", imageEmoji: "⛏️", exampleSentence: "They toiled in the fields all day.", category: "KA-5A" },
    { id: "ka5a-73", word: "Fertile", definition: "Good for growing plants", pronunciation: "/.../", imageEmoji: "🌱", exampleSentence: "The soil was very fertile.", category: "KA-5A" },
    { id: "ka5a-74", word: "Splendor", definition: "Great beauty", pronunciation: "/.../", imageEmoji: "✨", exampleSentence: "The palace was full of splendor.", category: "KA-5A" },
    { id: "ka5a-75", word: "Invaded", definition: "Attacked and entered", pronunciation: "/.../", imageEmoji: "⚔️", exampleSentence: "The army invaded the city.", category: "KA-5A" },
    { id: "ka5a-76", word: "Obstinate", definition: "Very stubborn", pronunciation: "/.../", imageEmoji: "🐂", exampleSentence: "He was too obstinate to change his mind.", category: "KA-5A" },
    { id: "ka5a-77", word: "Seized", definition: "Took by force", pronunciation: "/.../", imageEmoji: "✊", exampleSentence: "He seized the opportunity.", category: "KA-5A" },
    { id: "ka5a-78", word: "Merciful", definition: "Kind and forgiving", pronunciation: "/.../", imageEmoji: "🕊️", exampleSentence: "The king was merciful.", category: "KA-5A" },
    { id: "ka5a-79", word: "Soothing", definition: "Calming", pronunciation: "/.../", imageEmoji: "🍵", exampleSentence: "The music was soothing.", category: "KA-5A" },
    { id: "ka5a-80", word: "Caressed", definition: "Gently touched", pronunciation: "/.../", imageEmoji: "✋", exampleSentence: "She caressed the kitten.", category: "KA-5A" },
    { id: "ka5a-81", word: "Clutching", definition: "Holding tightly", pronunciation: "/.../", imageEmoji: "✊", exampleSentence: "He was clutching his bag.", category: "KA-5A" },
    { id: "ka5a-82", word: "Obtained", definition: "Got", pronunciation: "/.../", imageEmoji: "🎁", exampleSentence: "He obtained the necessary permits.", category: "KA-5A" },
    { id: "ka5a-83", word: "Tamed", definition: "Trained an animal", pronunciation: "/.../", imageEmoji: "🦁", exampleSentence: "The lion was tamed.", category: "KA-5A" },
    { id: "ka5a-84", word: "Scoundrel", definition: "Bad person", pronunciation: "/.../", imageEmoji: "🦹", exampleSentence: "That scoundrel stole my lunch!", category: "KA-5A" },
    { id: "ka5a-85", word: "Ludicrous", definition: "Very silly", pronunciation: "/.../", imageEmoji: "🤪", exampleSentence: "The idea was ludicrous.", category: "KA-5A" },
    { id: "ka5a-86", word: "Mischievous", definition: "Playful but naughty", pronunciation: "/.../", imageEmoji: "😈", exampleSentence: "The mischievous elf hid the toys.", category: "KA-5A" },
    { id: "ka5a-87", word: "Astonishment", definition: "Great surprise", pronunciation: "/.../", imageEmoji: "😲", exampleSentence: "He gasped in astonishment.", category: "KA-5A" },
    { id: "ka5a-88", word: "Stammered", definition: "Spoke with stops and pauses", pronunciation: "/.../", imageEmoji: "😶", exampleSentence: "He stammered his apology.", category: "KA-5A" },
    { id: "ka5a-89", word: "Cross", definition: "Angry", pronunciation: "/.../", imageEmoji: "😠", exampleSentence: "She was cross with him.", category: "KA-5A" },
    { id: "ka5a-90", word: "Transformed", definition: "Changed into something else", pronunciation: "/.../", imageEmoji: "🦋", exampleSentence: "The caterpillar transformed into a butterfly.", category: "KA-5A" },
    { id: "ka5a-91", word: "Tenacious", definition: "Not giving up", pronunciation: "/.../", imageEmoji: "🧗", exampleSentence: "He was tenacious in his efforts.", category: "KA-5A" },
    { id: "ka5a-92", word: "Reigned", definition: "Ruled", pronunciation: "/.../", imageEmoji: "👑", exampleSentence: "The queen reigned for many years.", category: "KA-5A" },
    { id: "ka5a-93", word: "Fugitive", definition: "Someone running from the law", pronunciation: "/.../", imageEmoji: "🏃", exampleSentence: "The fugitive hid in the woods.", category: "KA-5A" },
    { id: "ka5a-94", word: "Isolated", definition: "Lonely or alone", pronunciation: "/.../", imageEmoji: "🏝️", exampleSentence: "The island was isolated.", category: "KA-5A" },
    { id: "ka5a-95", word: "Intently", definition: "With strong focus", pronunciation: "/.../", imageEmoji: "🧐", exampleSentence: "She listened intently.", category: "KA-5A" },
    { id: "ka5a-96", word: "Persistence", definition: "Not giving up", pronunciation: "/.../", imageEmoji: "🔄", exampleSentence: "Her persistence paid off.", category: "KA-5A" },
    { id: "ka5a-97", word: "Retreat", definition: "Move away or escape", pronunciation: "/.../", imageEmoji: "🏳️", exampleSentence: "The army had to retreat.", category: "KA-5A" },
    { id: "ka5a-98", word: "Domination", definition: "Control over others", pronunciation: "/.../", imageEmoji: "🏰", exampleSentence: "They sought world domination.", category: "KA-5A" },
    { id: "ka5a-99", word: "Independence", definition: "Freedom", pronunciation: "/.../", imageEmoji: "🗽", exampleSentence: "They fought for independence.", category: "KA-5A" },
    { id: "ka5a-100", word: "Mutinous", definition: "Rebelling against leaders", pronunciation: "/.../", imageEmoji: "🏴‍☠️", exampleSentence: "The crew became mutinous.", category: "KA-5A" },
    { id: "ka5a-101", word: "Pleas", definition: "Requests for help", pronunciation: "/.../", imageEmoji: "🥺", exampleSentence: "They ignored his pleas for mercy.", category: "KA-5A" },
    { id: "ka5a-102", word: "Eerily", definition: "In a strange, scary way", pronunciation: "/.../", imageEmoji: "👻", exampleSentence: "It was eerily quiet.", category: "KA-5A" },
    { id: "ka5a-103", word: "Prudence", definition: "Careful thinking", pronunciation: "/.../", imageEmoji: "🧠", exampleSentence: "He acted with prudence.", category: "KA-5A" },
    { id: "ka5a-104", word: "Plantations", definition: "Very large farms", pronunciation: "/.../", imageEmoji: "🌾", exampleSentence: "They worked on the plantations.", category: "KA-5A" },
    { id: "ka5a-105", word: "Retire", definition: "Stop working because of age", pronunciation: "/.../", imageEmoji: "👴", exampleSentence: "He plans to retire soon.", category: "KA-5A" },
    { id: "ka5a-106", word: "Vulnerable", definition: "Easy to hurt", pronunciation: "/.../", imageEmoji: "🛡️", exampleSentence: "The small animal was vulnerable.", category: "KA-5A" },
    { id: "ka5a-107", word: "Adopted", definition: "Took into your family", pronunciation: "/.../", imageEmoji: "🏠", exampleSentence: "They adopted a puppy.", category: "KA-5A" },
    { id: "ka5a-108", word: "Vicious", definition: "Mean and violent", pronunciation: "/.../", imageEmoji: "🐊", exampleSentence: "The dog was vicious.", category: "KA-5A" },
    { id: "ka5a-109", word: "Ruthlessly", definition: "Very cruelly", pronunciation: "/.../", imageEmoji: "👿", exampleSentence: "He ruthlessly pursued his goals.", category: "KA-5A" },
    { id: "ka5a-110", word: "Grieving", definition: "Feeling deep sadness", pronunciation: "/.../", imageEmoji: "😢", exampleSentence: "They were grieving for their loss.", category: "KA-5A" },
    { id: "ka5a-111", word: "Desperate", definition: "Needing something very badly", pronunciation: "/.../", imageEmoji: "🆘", exampleSentence: "He was desperate for water.", category: "KA-5A" },
    { id: "ka5a-112", word: "Pledged", definition: "Promised", pronunciation: "/.../", imageEmoji: "🤝", exampleSentence: "He pledged his loyalty.", category: "KA-5A" },
    { id: "ka5a-113", word: "Determined", definition: "Decided and not quitting", pronunciation: "/.../", imageEmoji: "🎯", exampleSentence: "She was determined to win.", category: "KA-5A" },
    { id: "ka5a-114", word: "Accomplished", definition: "Finished successfully", pronunciation: "/.../", imageEmoji: "🏆", exampleSentence: "She is an accomplished pianist.", category: "KA-5A" },
    { id: "ka5a-115", word: "Herded", definition: "Moved together as a group", pronunciation: "/.../", imageEmoji: "🐑", exampleSentence: "The sheep were herded into the pen.", category: "KA-5A" },
    { id: "ka5a-116", word: "Prevailed", definition: "Won", pronunciation: "/.../", imageEmoji: "🚩", exampleSentence: "Justice prevailed in the end.", category: "KA-5A" },
    { id: "ka5a-117", word: "Vain", definition: "Too proud about looks or skills", pronunciation: "/.../", imageEmoji: "🪞", exampleSentence: "He was very vain about his hair.", category: "KA-5A" },
    { id: "ka5a-118", word: "Assumed", definition: "Thought something was true", pronunciation: "/.../", imageEmoji: "💭", exampleSentence: "I assumed you were coming.", category: "KA-5A" }
];
