import { VocabularyWord } from "./types";

export const KAAT_WORDS: VocabularyWord[] = [
    { id: 'kaat-1', word: 'Anticipate', definition: 'to think something will happen', pronunciation: '/ænˈtɪsɪpeɪt/', exampleSentence: 'We anticipate a good result.', imageEmoji: '🔮', category: 'KAAT' },
    { id: 'kaat-2', word: 'Courteous', definition: 'kind and polite to others', pronunciation: '/ˈkɜːrtiəs/', exampleSentence: 'He is very courteous.', imageEmoji: '🎩', category: 'KAAT' },
    { id: 'kaat-3', word: 'Sheepish', definition: 'feeling shy or embarrassed', pronunciation: '/ˈʃiːpɪʃ/', exampleSentence: 'A sheepish smile.', imageEmoji: '😳', category: 'KAAT' },
    { id: 'kaat-4', word: 'Tease', definition: 'to make fun of someone', pronunciation: '/tiːz/', exampleSentence: 'Don\'t tease your brother.', imageEmoji: '😜', category: 'KAAT' },
    { id: 'kaat-5', word: 'Enrich', definition: 'to make something better', pronunciation: '/ɪnˈrɪtʃ/', exampleSentence: 'Enrich your mind.', imageEmoji: '✨', category: 'KAAT' },
    { id: 'kaat-6', word: 'Perturbed', definition: 'feeling upset or worried', pronunciation: '/pərˈtɜːrbd/', exampleSentence: 'She looked perturbed.', imageEmoji: '😟', category: 'KAAT' },
    { id: 'kaat-7', word: 'Tirelessly', definition: 'without getting tired', pronunciation: '/ˈtaɪərləsli/', exampleSentence: 'Work tirelessly.', imageEmoji: '🏃', category: 'KAAT' },
    { id: 'kaat-8', word: 'Ultimate', definition: 'the last or most important', pronunciation: '/ˈʌltɪmət/', exampleSentence: 'The ultimate prize.', imageEmoji: '🏆', category: 'KAAT' },
    { id: 'kaat-9', word: 'Guzzle', definition: 'to drink very fast', pronunciation: '/ˈɡʌzl/', exampleSentence: 'Guzzle the water.', imageEmoji: '🥤', category: 'KAAT' },
    { id: 'kaat-10', word: 'Malicious', definition: 'wanting to hurt someone', pronunciation: '/məˈlɪʃəs/', exampleSentence: 'Malicious intent.', imageEmoji: '😈', category: 'KAAT' },
    { id: 'kaat-11', word: 'Resistant', definition: 'not wanting to change or agree', pronunciation: '/rɪˈzɪstənt/', exampleSentence: 'Resistant to change.', imageEmoji: '🛡️', category: 'KAAT' },
    { id: 'kaat-12', word: 'Tragedy', definition: 'a very sad event', pronunciation: '/ˈtrædʒədi/', exampleSentence: 'A terrible tragedy.', imageEmoji: '🎭', category: 'KAAT' },
    { id: 'kaat-13', word: 'Pronounce', definition: 'to say a word correctly', pronunciation: '/prəˈnaʊns/', exampleSentence: 'Pronounce it clearly.', imageEmoji: '🗣️', category: 'KAAT' },
    { id: 'kaat-14', word: 'Hero', definition: 'a brave person who helps others', pronunciation: '/ˈhɪroʊ/', exampleSentence: 'A superhero.', imageEmoji: '🦸', category: 'KAAT' },
    { id: 'kaat-15', word: 'Nutrition', definition: 'food that helps your body grow', pronunciation: '/nuˈtrɪʃn/', exampleSentence: 'Good nutrition.', imageEmoji: '🥗', category: 'KAAT' },
    { id: 'kaat-16', word: 'Tenacious', definition: 'not giving up easily', pronunciation: '/təˈneɪʃəs/', exampleSentence: 'Tenacious effort.', imageEmoji: '💪', category: 'KAAT' },
    { id: 'kaat-17', word: 'Immigrant', definition: 'a person who moves to a new country', pronunciation: '/ˈɪmɪɡrənt/', exampleSentence: 'A new immigrant.', imageEmoji: '🧳', category: 'KAAT' },
    { id: 'kaat-18', word: 'Hope', definition: 'wanting good things to happen', pronunciation: '/hoʊp/', exampleSentence: 'Never lose hope.', imageEmoji: '🕊️', category: 'KAAT' },
    { id: 'kaat-19', word: 'Employ', definition: 'to give someone a job', pronunciation: '/ɪmˈplɔɪ/', exampleSentence: 'Employ new staff.', imageEmoji: '🤝', category: 'KAAT' },
    { id: 'kaat-20', word: 'Audible', definition: 'able to be heard', pronunciation: '/ˈɔːdəbl/', exampleSentence: 'Is it audible?', imageEmoji: '🔊', category: 'KAAT' },
    { id: 'kaat-21', word: 'Essential', definition: 'very important; needed', pronunciation: '/ɪˈsɛnʃl/', exampleSentence: 'Water is essential.', imageEmoji: '💧', category: 'KAAT' },
    { id: 'kaat-22', word: 'Affluent', definition: 'having a lot of money', pronunciation: '/ˈæfluənt/', exampleSentence: 'An affluent neighborhood.', imageEmoji: '💰', category: 'KAAT' },
    { id: 'kaat-23', word: 'Demonstrate', definition: 'show how something works', pronunciation: '/ˈdɛmənstreɪt/', exampleSentence: 'Let me demonstrate.', imageEmoji: '👉', category: 'KAAT' },
    { id: 'kaat-24', word: 'Extend', definition: 'make longer', pronunciation: '/ɪkˈstɛnd/', exampleSentence: 'Extend the deadline.', imageEmoji: '📏', category: 'KAAT' },
    { id: 'kaat-25', word: 'Benefit', definition: 'something good that helps you', pronunciation: '/ˈbɛnɪfɪt/', exampleSentence: 'For your benefit.', imageEmoji: '➕', category: 'KAAT' },
    { id: 'kaat-26', word: 'Disintegration', definition: 'breaking into small pieces', pronunciation: '/dɪsˌɪntɪˈɡreɪʃn/', exampleSentence: 'The rock\'s disintegration.', imageEmoji: '🧩', category: 'KAAT' },
    { id: 'kaat-27', word: 'Caution', definition: 'a warning to be careful', pronunciation: '/ˈkɔːʃn/', exampleSentence: 'Proceed with caution.', imageEmoji: '⚠️', category: 'KAAT' },
    { id: 'kaat-28', word: 'Priority', definition: 'something that comes first', pronunciation: '/praɪˈɔːrəti/', exampleSentence: 'Top priority.', imageEmoji: '1️⃣', category: 'KAAT' },
    { id: 'kaat-29', word: 'Implore', definition: 'to beg someone very strongly', pronunciation: '/ɪmˈplɔːr/', exampleSentence: 'I implore you to help.', imageEmoji: '🙏', category: 'KAAT' },
    { id: 'kaat-30', word: 'Surmise', definition: 'to make a smart guess', pronunciation: '/sərˈmaɪz/', exampleSentence: 'I surmise he is late.', imageEmoji: '🤔', category: 'KAAT' },
    { id: 'kaat-31', word: 'Detestable', definition: 'very unpleasant or awful', pronunciation: '/dɪˈtɛstəbl/', exampleSentence: 'A detestable crime.', imageEmoji: '😠', category: 'KAAT' },
    { id: 'kaat-32', word: 'Flawed', definition: 'not perfect; has a problem', pronunciation: '/flɔːd/', exampleSentence: 'A flawed plan.', imageEmoji: '❌', category: 'KAAT' },
    { id: 'kaat-33', word: 'Calculate', definition: 'work out an answer using numbers', pronunciation: '/ˈkælkjuleɪt/', exampleSentence: 'Calculate the total.', imageEmoji: '🧮', category: 'KAAT' },
    { id: 'kaat-34', word: 'Relinquish', definition: 'give something up', pronunciation: '/rɪˈlɪŋkwɪʃ/', exampleSentence: 'Relinquish control.', imageEmoji: '🏳️', category: 'KAAT' },
    { id: 'kaat-35', word: 'Scornfully', definition: 'in a mean or rude way', pronunciation: '/ˈskɔːrnfəli/', exampleSentence: 'She looked scornfully.', imageEmoji: '😒', category: 'KAAT' },
    { id: 'kaat-36', word: 'Dread', definition: 'feel very scared about something', pronunciation: '/drɛd/', exampleSentence: 'I dread the test.', imageEmoji: '😨', category: 'KAAT' },
    { id: 'kaat-37', word: 'Persuade', definition: 'make someone agree or do something', pronunciation: '/pərˈsweɪd/', exampleSentence: 'Try to persuade him.', imageEmoji: '🗣️', category: 'KAAT' },
    { id: 'kaat-38', word: 'Approach', definition: 'a way of doing something', pronunciation: '/əˈproʊtʃ/', exampleSentence: 'A new approach.', imageEmoji: '🚶', category: 'KAAT' },
    { id: 'kaat-39', word: 'Abundant', definition: 'more than enough', pronunciation: '/əˈbʌndənt/', exampleSentence: 'Abundant food.', imageEmoji: '🧺', category: 'KAAT' },
    { id: 'kaat-40', word: 'Similar', definition: 'almost the same', pronunciation: '/ˈsɪmɪlər/', exampleSentence: 'They look similar.', imageEmoji: '👯', category: 'KAAT' }
];
