import { VocabularyWord } from "./types";

export const PRE_1_WORDS: VocabularyWord[] = [
    { id: "pre1-1", word: "Accountability", definition: "Being responsible for what you do", pronunciation: "/.../", imageEmoji: "📋", exampleSentence: "Accountability is important in a team.", category: "Pre-1" },
    { id: "pre1-2", word: "Boycott", definition: "To refuse to buy or use something to show disagreement", pronunciation: "/.../", imageEmoji: "🚫", exampleSentence: "They decided to boycott the store.", category: "Pre-1" },
    { id: "pre1-3", word: "Affluent", definition: "Rich; having a lot of money", pronunciation: "/.../", imageEmoji: "💰", exampleSentence: "The family was very affluent.", category: "Pre-1" },
    { id: "pre1-4", word: "Scrutiny", definition: "Looking at something very carefully", pronunciation: "/.../", imageEmoji: "🧐", exampleSentence: "The plan came under close scrutiny.", category: "Pre-1" },
    { id: "pre1-5", word: "Advocate", definition: "A person who supports or speaks up for others", pronunciation: "/.../", imageEmoji: "🗣️", exampleSentence: "She is an advocate for animal rights.", category: "Pre-1" },
    { id: "pre1-6", word: "Ambiguous", definition: "Not clear; confusing", pronunciation: "/.../", imageEmoji: "❓", exampleSentence: "The instructions were ambiguous.", category: "Pre-1" },
    { id: "pre1-7", word: "Asset", definition: "Something useful or valuable", pronunciation: "/.../", imageEmoji: "💎", exampleSentence: "Good health is a great asset.", category: "Pre-1" },
    { id: "pre1-8", word: "Mandate", definition: "An official order", pronunciation: "/.../", imageEmoji: "📜", exampleSentence: "The government issued a new mandate.", category: "Pre-1" },
    { id: "pre1-9", word: "Nuance", definition: "A small detail that is easy to miss", pronunciation: "/.../", imageEmoji: "🔍", exampleSentence: "He explained the nuance of the word.", category: "Pre-1" },
    { id: "pre1-10", word: "Dilemma", definition: "A hard choice between two options", pronunciation: "/.../", imageEmoji: "🤔", exampleSentence: "She faced a difficult dilemma.", category: "Pre-1" },
    { id: "pre1-11", word: "Consensus", definition: "When everyone agrees", pronunciation: "/.../", imageEmoji: "🤝", exampleSentence: "The group reached a consensus.", category: "Pre-1" },
    { id: "pre1-12", word: "Debunk", definition: "To prove something is false", pronunciation: "/.../", imageEmoji: "❌", exampleSentence: "He wanted to debunk the myth.", category: "Pre-1" },
    { id: "pre1-13", word: "Curtail", definition: "To make something shorter or smaller", pronunciation: "/.../", imageEmoji: "✂️", exampleSentence: "We had to curtail the meeting.", category: "Pre-1" },
    { id: "pre1-14", word: "Legislation", definition: "Laws made by the government", pronunciation: "/.../", imageEmoji: "⚖️", exampleSentence: "New legislation was passed today.", category: "Pre-1" },
    { id: "pre1-15", word: "Candid", definition: "Honest and truthful", pronunciation: "/.../", imageEmoji: "👐", exampleSentence: "She gave a candid answer.", category: "Pre-1" },
    { id: "pre1-16", word: "Mitigate", definition: "To make something less bad", pronunciation: "/.../", imageEmoji: "🛡️", exampleSentence: "They tried to mitigate the damage.", category: "Pre-1" },
    { id: "pre1-17", word: "Inquire", definition: "To ask questions", pronunciation: "/.../", imageEmoji: "👋", exampleSentence: "I will inquire about the schedule.", category: "Pre-1" },
    { id: "pre1-18", word: "Monopoly", definition: "When one group controls everything", pronunciation: "/.../", imageEmoji: "🎩", exampleSentence: "The company has a monopoly on oil.", category: "Pre-1" },
    { id: "pre1-19", word: "Endorse", definition: "To approve or support", pronunciation: "/.../", imageEmoji: "✔️", exampleSentence: "I can endorse this candidate.", category: "Pre-1" },
    { id: "pre1-20", word: "Deter", definition: "To stop someone from doing something", pronunciation: "/.../", imageEmoji: "🛑", exampleSentence: "The fence helps deter intruders.", category: "Pre-1" },
    { id: "pre1-21", word: "Viable", definition: "Able to work or succeed", pronunciation: "/.../", imageEmoji: "🌱", exampleSentence: "Is this a viable plan?", category: "Pre-1" },
    { id: "pre1-22", word: "Ostracize", definition: "To leave someone out on purpose", pronunciation: "/.../", imageEmoji: "😠", exampleSentence: "Don't ostracize the new student.", category: "Pre-1" },
    { id: "pre1-23", word: "Propel", definition: "To push something forward", pronunciation: "/.../", imageEmoji: "🚀", exampleSentence: "The wind helped propel the boat.", category: "Pre-1" },
    { id: "pre1-24", word: "Disparity", definition: "A big difference", pronunciation: "/.../", imageEmoji: "📏", exampleSentence: "There is a disparity in their ages.", category: "Pre-1" },
    { id: "pre1-25", word: "Acknowledge", definition: "To notice or admit something", pronunciation: "/.../", imageEmoji: "👀", exampleSentence: "Please acknowledge my email.", category: "Pre-1" },
    { id: "pre1-26", word: "Tariff", definition: "A tax on goods from other countries", pronunciation: "/.../", imageEmoji: "🛂", exampleSentence: "The government added a new tariff.", category: "Pre-1" },
    { id: "pre1-27", word: "Perplexing", definition: "Very confusing", pronunciation: "/.../", imageEmoji: "😵‍💫", exampleSentence: "The puzzle was perplexing.", category: "Pre-1" },
    { id: "pre1-28", word: "Disburse", definition: "To give out money", pronunciation: "/.../", imageEmoji: "💸", exampleSentence: "The bank will disburse the funds.", category: "Pre-1" },
    { id: "pre1-29", word: "Paradigm", definition: "A common example or model", pronunciation: "/.../", imageEmoji: "📐", exampleSentence: "This is a new paradigm for learning.", category: "Pre-1" },
    { id: "pre1-30", word: "Liability", definition: "Being responsible for a problem", pronunciation: "/.../", imageEmoji: "⚠️", exampleSentence: "He admitted liability for the accident.", category: "Pre-1" },
    { id: "pre1-31", word: "Erode", definition: "To slowly wear away", pronunciation: "/.../", imageEmoji: "🌊", exampleSentence: "The water will erode the rock.", category: "Pre-1" },
    { id: "pre1-32", word: "Stipulate", definition: "To clearly state a rule", pronunciation: "/.../", imageEmoji: "📝", exampleSentence: "The contract will stipulate the terms.", category: "Pre-1" },
    { id: "pre1-33", word: "Subsidy", definition: "Money given to help", pronunciation: "/.../", imageEmoji: "💵", exampleSentence: "Farmers received a subsidy.", category: "Pre-1" },
    { id: "pre1-34", word: "Unprecedented", definition: "Never happened before", pronunciation: "/.../", imageEmoji: "🤯", exampleSentence: "This event is unprecedented.", category: "Pre-1" },
    { id: "pre1-35", word: "Fluctuate", definition: "To go up and down", pronunciation: "/.../", imageEmoji: "📉", exampleSentence: "Prices tend to fluctuate.", category: "Pre-1" },
    { id: "pre1-36", word: "Devise", definition: "To plan or create something", pronunciation: "/.../", imageEmoji: "💡", exampleSentence: "We must devise a strategy.", category: "Pre-1" },
    { id: "pre1-37", word: "Convene", definition: "To meet together", pronunciation: "/.../", imageEmoji: "👥", exampleSentence: "The committee will convene tomorrow.", category: "Pre-1" },
    { id: "pre1-38", word: "Premise", definition: "An idea you start with", pronunciation: "/.../", imageEmoji: "🏗️", exampleSentence: "The movie is based on a simple premise.", category: "Pre-1" },
    { id: "pre1-39", word: "Quell", definition: "To stop something quickly", pronunciation: "/.../", imageEmoji: "✋", exampleSentence: "He tried to quell the rumors.", category: "Pre-1" },
    { id: "pre1-40", word: "Allegiance", definition: "Strong loyalty", pronunciation: "/.../", imageEmoji: "🎗️", exampleSentence: "They pledge allegiance to the flag.", category: "Pre-1" },
    { id: "pre1-41", word: "Discretion", definition: "Making careful choices", pronunciation: "/.../", imageEmoji: "🤫", exampleSentence: "Use your own discretion.", category: "Pre-1" },
    { id: "pre1-42", word: "Aesthetic", definition: "About how something looks", pronunciation: "/.../", imageEmoji: "🎨", exampleSentence: "I like the aesthetic of this room.", category: "Pre-1" },
    { id: "pre1-43", word: "Prescribe", definition: "To officially say what should be done", pronunciation: "/.../", imageEmoji: "💊", exampleSentence: "The doctor will prescribe medicine.", category: "Pre-1" },
    { id: "pre1-44", word: "Deficit", definition: "Not having enough", pronunciation: "/.../", imageEmoji: "📉", exampleSentence: "There is a budget deficit.", category: "Pre-1" },
    { id: "pre1-45", word: "Reimburse", definition: "To pay someone back", pronunciation: "/.../", imageEmoji: "💳", exampleSentence: "We will reimburse your expenses.", category: "Pre-1" },
    { id: "pre1-46", word: "Juxtapose", definition: "To put things side by side to compare", pronunciation: "/.../", imageEmoji: "🌗", exampleSentence: "Juxtapose the two images.", category: "Pre-1" },
    { id: "pre1-47", word: "Vigilant", definition: "Very careful and watchful", pronunciation: "/.../", imageEmoji: "🦉", exampleSentence: "Security guards must be vigilant.", category: "Pre-1" },
    { id: "pre1-48", word: "Impose", definition: "To force rules on someone", pronunciation: "/.../", imageEmoji: "👮", exampleSentence: "Do not impose your views on others.", category: "Pre-1" },
    { id: "pre1-49", word: "Elaborate", definition: "Having many details", pronunciation: "/.../", imageEmoji: "🕸️", exampleSentence: "The design was very elaborate.", category: "Pre-1" },
    { id: "pre1-50", word: "Instigate", definition: "To start trouble", pronunciation: "/.../", imageEmoji: "🔥", exampleSentence: "Don't instigate a fight.", category: "Pre-1" },
    { id: "pre1-51", word: "Commission", definition: "A group given a job to do", pronunciation: "/.../", imageEmoji: "🏢", exampleSentence: "The commission released a report.", category: "Pre-1" },
    { id: "pre1-52", word: "Contend", definition: "To compete or argue", pronunciation: "/.../", imageEmoji: "🥊", exampleSentence: "He has to contend with many problems.", category: "Pre-1" },
    { id: "pre1-53", word: "Ubiquitous", definition: "Seen everywhere", pronunciation: "/.../", imageEmoji: "🌐", exampleSentence: "Smartphones are ubiquitous now.", category: "Pre-1" },
    { id: "pre1-54", word: "Epilogue", definition: "The ending part of a story", pronunciation: "/.../", imageEmoji: "📖", exampleSentence: "Read the epilogue for closure.", category: "Pre-1" },
    { id: "pre1-55", word: "Prejudice", definition: "Unfair ideas about others", pronunciation: "/.../", imageEmoji: "🙈", exampleSentence: "We must fight against prejudice.", category: "Pre-1" },
    { id: "pre1-56", word: "Inherent", definition: "Naturally part of something", pronunciation: "/.../", imageEmoji: "🧬", exampleSentence: "There are inherent risks in flying.", category: "Pre-1" },
    { id: "pre1-57", word: "Apprehend", definition: "To catch or arrest someone", pronunciation: "/.../", imageEmoji: "👮‍♂️", exampleSentence: "Police hope to apprehend the thief.", category: "Pre-1" }
];
