import { VocabularyWord } from './types';

export const SAT_WORDS: VocabularyWord[] = [
    // 1-50
    { id: 'sat-1', word: 'Impact', definition: 'strong effect', pronunciation: '/ˈɪmpækt/', exampleSentence: 'The crash had a big impact.', imageEmoji: '💥', category: 'SAT' },
    { id: 'sat-2', word: 'Maintain', definition: 'keep the same', pronunciation: '/meɪnˈteɪn/', exampleSentence: 'Maintain your speed.', imageEmoji: '🔧', category: 'SAT' },
    { id: 'sat-3', word: 'Abate', definition: 'become less', pronunciation: '/əˈbeɪt/', exampleSentence: 'The storm will abate.', imageEmoji: '📉', category: 'SAT' },
    { id: 'sat-4', word: 'Evidence', definition: 'proof', pronunciation: '/ˈevɪdəns/', exampleSentence: 'Show me the evidence.', imageEmoji: '🔎', category: 'SAT' },
    { id: 'sat-5', word: 'Trend', definition: 'something becoming popular', pronunciation: '/trend/', exampleSentence: 'A new fashion trend.', imageEmoji: '📈', category: 'SAT' },
    { id: 'sat-6', word: 'Establish', definition: 'set up', pronunciation: '/ɪˈstæblɪʃ/', exampleSentence: 'Establish a new rule.', imageEmoji: '🏗️', category: 'SAT' },
    { id: 'sat-7', word: 'Interpret', definition: 'explain meaning', pronunciation: '/ɪnˈtɜːrprət/', exampleSentence: 'Interpret the dream.', imageEmoji: '🗣️', category: 'SAT' },
    { id: 'sat-8', word: 'Significant', definition: 'important', pronunciation: '/sɪɡˈnɪfɪkənt/', exampleSentence: 'A significant change.', imageEmoji: '❗', category: 'SAT' },
    { id: 'sat-9', word: 'Generate', definition: 'make', pronunciation: '/ˈdʒenəreɪt/', exampleSentence: 'Generate power.', imageEmoji: '⚡', category: 'SAT' },
    { id: 'sat-10', word: 'Context', definition: 'situation around something', pronunciation: '/ˈkɑːntekst/', exampleSentence: 'In this context...', imageEmoji: '🖼️', category: 'SAT' },
    { id: 'sat-11', word: 'Approach', definition: 'way of doing something', pronunciation: '/əˈproʊtʃ/', exampleSentence: 'A new approach.', imageEmoji: '🚶', category: 'SAT' },
    { id: 'sat-12', word: 'Sustain', definition: 'keep going', pronunciation: '/səˈsteɪn/', exampleSentence: 'Sustain the effort.', imageEmoji: '🔋', category: 'SAT' },
    { id: 'sat-13', word: 'Factor', definition: 'something that affects results', pronunciation: '/ˈfæktər/', exampleSentence: 'A key factor.', imageEmoji: '🧩', category: 'SAT' },
    { id: 'sat-14', word: 'Adapt', definition: 'change to fit', pronunciation: '/əˈdæpt/', exampleSentence: 'Adapt to the weather.', imageEmoji: '🦎', category: 'SAT' },
    { id: 'sat-15', word: 'Consequence', definition: 'what happens because', pronunciation: '/ˈkɑːnsɪkwens/', exampleSentence: 'Face the consequence.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-16', word: 'Analyze', definition: 'look at closely', pronunciation: '/ˈænəlaɪz/', exampleSentence: 'Analyze the data.', imageEmoji: '🔬', category: 'SAT' },
    { id: 'sat-17', word: 'Relevant', definition: 'related and important', pronunciation: '/ˈreləvənt/', exampleSentence: 'Relevant information.', imageEmoji: '📎', category: 'SAT' },
    { id: 'sat-18', word: 'Indicate', definition: 'show', pronunciation: '/ˈɪndɪkeɪt/', exampleSentence: 'Signs indicate rain.', imageEmoji: '👉', category: 'SAT' },
    { id: 'sat-19', word: 'Structure', definition: 'how something is built', pronunciation: '/ˈstrʌktʃər/', exampleSentence: 'Strong structure.', imageEmoji: '🏛️', category: 'SAT' },
    { id: 'sat-20', word: 'Outcome', definition: 'result', pronunciation: '/ˈaʊtkʌm/', exampleSentence: 'Good outcome.', imageEmoji: '🏁', category: 'SAT' },
    { id: 'sat-21', word: 'Acquire', definition: 'get', pronunciation: '/əˈkwaɪər/', exampleSentence: 'Acquire knowledge.', imageEmoji: '📚', category: 'SAT' },
    { id: 'sat-22', word: 'Assume', definition: 'think something is true', pronunciation: '/əˈsuːm/', exampleSentence: 'I assume you know.', imageEmoji: '🤔', category: 'SAT' },
    { id: 'sat-23', word: 'Diverse', definition: 'many kinds', pronunciation: '/dɪˈvɜːrs/', exampleSentence: 'Diverse group.', imageEmoji: '🌈', category: 'SAT' },
    { id: 'sat-24', word: 'Clarify', definition: 'make clear', pronunciation: '/ˈklærəfaɪ/', exampleSentence: 'Clarify your point.', imageEmoji: '👓', category: 'SAT' },
    { id: 'sat-25', word: 'Evaluate', definition: 'judge how good', pronunciation: '/ɪˈvæljueɪt/', exampleSentence: 'Evaluate the work.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-26', word: 'Contrast', definition: 'see differences', pronunciation: '/ˈkɑːntræst/', exampleSentence: 'Compare and contrast.', imageEmoji: '🌗', category: 'SAT' },
    { id: 'sat-27', word: 'Constant', definition: 'not changing', pronunciation: '/ˈkɑːnstənt/', exampleSentence: 'Constant noise.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-28', word: 'Modify', definition: 'change a little', pronunciation: '/ˈmɑːdɪfaɪ/', exampleSentence: 'Modify the plan.', imageEmoji: '✏️', category: 'SAT' },
    { id: 'sat-29', word: 'Limit', definition: 'point you cannot pass', pronunciation: '/ˈlɪmɪt/', exampleSentence: 'Speed limit.', imageEmoji: '🛑', category: 'SAT' },
    { id: 'sat-30', word: 'Enable', definition: 'make possible', pronunciation: '/ɪˈneɪbl/', exampleSentence: 'Enable the feature.', imageEmoji: '🔓', category: 'SAT' },
    { id: 'sat-31', word: 'Contribute', definition: 'help add', pronunciation: '/kənˈtrɪbjuːt/', exampleSentence: 'Contribute money.', imageEmoji: '🤝', category: 'SAT' },
    { id: 'sat-32', word: 'Function', definition: 'job something does', pronunciation: '/ˈfʌŋkʃn/', exampleSentence: 'Its function is to cut.', imageEmoji: '⚙️', category: 'SAT' },
    { id: 'sat-33', word: 'Demonstrate', definition: 'show', pronunciation: '/ˈdemənstreɪt/', exampleSentence: 'Demonstrate how.', imageEmoji: '👨‍🏫', category: 'SAT' },
    { id: 'sat-34', word: 'Participate', definition: 'take part', pronunciation: '/pɑːrˈtɪsɪpeɪt/', exampleSentence: 'Participate in games.', imageEmoji: '🙋', category: 'SAT' },
    { id: 'sat-35', word: 'Policy', definition: 'rule or plan', pronunciation: '/ˈpɑːləsi/', exampleSentence: 'School policy.', imageEmoji: '📜', category: 'SAT' },
    { id: 'sat-36', word: 'Process', definition: 'steps', pronunciation: '/ˈprɑːses/', exampleSentence: 'A long process.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-37', word: 'Predict', definition: 'guess what happens next', pronunciation: '/prɪˈdɪkt/', exampleSentence: 'Predict the winner.', imageEmoji: '🔮', category: 'SAT' },
    { id: 'sat-38', word: 'Promote', definition: 'help grow', pronunciation: '/prəˈmoʊt/', exampleSentence: 'Promote health.', imageEmoji: '📢', category: 'SAT' },
    { id: 'sat-39', word: 'Source', definition: 'where something comes from', pronunciation: '/sɔːrs/', exampleSentence: 'Source of light.', imageEmoji: '☀️', category: 'SAT' },
    { id: 'sat-40', word: 'Specific', definition: 'exact', pronunciation: '/spəˈsɪfɪk/', exampleSentence: 'Be specific.', imageEmoji: '🎯', category: 'SAT' },
    { id: 'sat-41', word: 'Region', definition: 'area', pronunciation: '/ˈriːdʒən/', exampleSentence: 'Desert region.', imageEmoji: '🗺️', category: 'SAT' },
    { id: 'sat-42', word: 'Method', definition: 'way to do something', pronunciation: '/ˈmeθəd/', exampleSentence: 'Scientific method.', imageEmoji: '🧪', category: 'SAT' },
    { id: 'sat-43', word: 'Monitor', definition: 'watch closely', pronunciation: '/ˈmɑːnɪtər/', exampleSentence: 'Monitor the screen.', imageEmoji: '🖥️', category: 'SAT' },
    { id: 'sat-44', word: 'Decline', definition: 'go down', pronunciation: '/dɪˈklaɪn/', exampleSentence: 'Prices decline.', imageEmoji: '📉', category: 'SAT' },
    { id: 'sat-45', word: 'Respond', definition: 'answer', pronunciation: '/rɪˈspɑːnd/', exampleSentence: 'Respond quickly.', imageEmoji: '↩️', category: 'SAT' },
    { id: 'sat-46', word: 'Role', definition: 'part someone plays', pronunciation: '/roʊl/', exampleSentence: 'Role in the play.', imageEmoji: '🎭', category: 'SAT' },
    { id: 'sat-47', word: 'Survey', definition: 'study or ask questions', pronunciation: '/ˈsɜːrveɪ/', exampleSentence: 'Take a survey.', imageEmoji: '📋', category: 'SAT' },
    { id: 'sat-48', word: 'Technique', definition: 'special way', pronunciation: '/tekˈniːk/', exampleSentence: 'Painting technique.', imageEmoji: '🎨', category: 'SAT' },
    { id: 'sat-49', word: 'Theory', definition: 'idea that explains', pronunciation: '/ˈθɪri/', exampleSentence: 'Big Bang Theory.', imageEmoji: '🌌', category: 'SAT' },
    { id: 'sat-50', word: 'Variable', definition: 'something that changes', pronunciation: '/ˈveriəbl/', exampleSentence: 'Unknown variable.', imageEmoji: '🔣', category: 'SAT' },

    // 51-100
    { id: 'sat-51', word: 'Occur', definition: 'happen', pronunciation: '/əˈkɜːr/', exampleSentence: 'When did it occur?', imageEmoji: '📅', category: 'SAT' },
    { id: 'sat-52', word: 'Range', definition: 'group between limits', pronunciation: '/reɪndʒ/', exampleSentence: 'A wide range.', imageEmoji: '↔️', category: 'SAT' },
    { id: 'sat-53', word: 'Reflect', definition: 'show or think back', pronunciation: '/rɪˈflekt/', exampleSentence: 'Reflect on the past.', imageEmoji: '🪞', category: 'SAT' },
    { id: 'sat-54', word: 'Reduce', definition: 'make smaller', pronunciation: '/rɪˈduːs/', exampleSentence: 'Reduce waste.', imageEmoji: '♻️', category: 'SAT' },
    { id: 'sat-55', word: 'Increase', definition: 'grow bigger', pronunciation: '/ɪnˈkriːs/', exampleSentence: 'Increase speed.', imageEmoji: '🚀', category: 'SAT' },
    { id: 'sat-56', word: 'Influence', definition: 'affect', pronunciation: '/ˈɪnfluəns/', exampleSentence: 'Good influence.', imageEmoji: '👍', category: 'SAT' },
    { id: 'sat-57', word: 'Interpretation', definition: 'explanation', pronunciation: '/ɪnˌtɜːrprəˈteɪʃn/', exampleSentence: 'My interpretation.', imageEmoji: '🗣️', category: 'SAT' },
    { id: 'sat-58', word: 'Identify', definition: 'name or find', pronunciation: '/aɪˈdentɪfaɪ/', exampleSentence: 'Identify the problem.', imageEmoji: '🔍', category: 'SAT' },
    { id: 'sat-59', word: 'Major', definition: 'very important', pronunciation: '/ˈmeɪdʒər/', exampleSentence: 'Major event.', imageEmoji: '⭐', category: 'SAT' },
    { id: 'sat-60', word: 'Minor', definition: 'less important', pronunciation: '/ˈmaɪnər/', exampleSentence: 'Minor detail.', imageEmoji: '🤏', category: 'SAT' },
    { id: 'sat-61', word: 'Framework', definition: 'basic structure', pronunciation: '/ˈfreɪmwɜːrk/', exampleSentence: 'Building framework.', imageEmoji: '🏗️', category: 'SAT' },
    { id: 'sat-62', word: 'Illustrate', definition: 'show with examples', pronunciation: '/ˈɪləstreɪt/', exampleSentence: 'Illustrate the point.', imageEmoji: '🖍️', category: 'SAT' },
    { id: 'sat-63', word: 'Initial', definition: 'first', pronunciation: '/ɪˈnɪʃl/', exampleSentence: 'Initial step.', imageEmoji: '1️⃣', category: 'SAT' },
    { id: 'sat-64', word: 'Innovation', definition: 'new idea', pronunciation: '/ˌɪnəˈveɪʃn/', exampleSentence: 'Tech innovation.', imageEmoji: '💡', category: 'SAT' },
    { id: 'sat-65', word: 'Instance', definition: 'example', pronunciation: '/ˈɪnstəns/', exampleSentence: 'For instance.', imageEmoji: '👉', category: 'SAT' },
    { id: 'sat-66', word: 'Interaction', definition: 'working together', pronunciation: '/ˌɪntərˈækʃn/', exampleSentence: 'Social interaction.', imageEmoji: '🗣️', category: 'SAT' },
    { id: 'sat-67', word: 'Logic', definition: 'clear thinking', pronunciation: '/ˈlɑːdʒɪk/', exampleSentence: 'Use logic.', imageEmoji: '🧠', category: 'SAT' },
    { id: 'sat-68', word: 'Majority', definition: 'more than half', pronunciation: '/məˈdʒɔːrəti/', exampleSentence: 'The majority voted.', imageEmoji: '✋', category: 'SAT' },
    { id: 'sat-69', word: 'Neutral', definition: 'not taking sides', pronunciation: '/ˈnuːtrəl/', exampleSentence: 'Stay neutral.', imageEmoji: '😐', category: 'SAT' },
    { id: 'sat-70', word: 'Objective', definition: 'goal', pronunciation: '/əbˈdʒektɪv/', exampleSentence: 'Main objective.', imageEmoji: '🎯', category: 'SAT' },
    { id: 'sat-71', word: 'Obtain', definition: 'get', pronunciation: '/əbˈteɪn/', exampleSentence: 'Obtain permission.', imageEmoji: '🤲', category: 'SAT' },
    { id: 'sat-72', word: 'Oppose', definition: 'disagree', pronunciation: '/əˈpoʊz/', exampleSentence: 'Oppose the law.', imageEmoji: '🛑', category: 'SAT' },
    { id: 'sat-73', word: 'Perspective', definition: 'point of view', pronunciation: '/pərˈspektɪv/', exampleSentence: 'New perspective.', imageEmoji: '🔭', category: 'SAT' },
    { id: 'sat-74', word: 'Phenomenon', definition: 'something that happens', pronunciation: '/fəˈnɑːmɪnən/', exampleSentence: 'Natural phenomenon.', imageEmoji: '🌋', category: 'SAT' },
    { id: 'sat-75', word: 'Potential', definition: 'possible', pronunciation: '/pəˈtenʃl/', exampleSentence: 'Great potential.', imageEmoji: '🚀', category: 'SAT' },
    { id: 'sat-76', word: 'Primary', definition: 'main', pronunciation: '/ˈpraɪmeri/', exampleSentence: 'Primary cause.', imageEmoji: '☝️', category: 'SAT' },
    { id: 'sat-77', word: 'Principle', definition: 'basic rule', pronunciation: '/ˈprɪnsəpl/', exampleSentence: 'Moral principle.', imageEmoji: '📜', category: 'SAT' },
    { id: 'sat-78', word: 'Procedure', definition: 'steps', pronunciation: '/prəˈsiːdʒər/', exampleSentence: 'Safety procedure.', imageEmoji: '📋', category: 'SAT' },
    { id: 'sat-79', word: 'Random', definition: 'without plan', pronunciation: '/ˈrændəm/', exampleSentence: 'Random choice.', imageEmoji: '🎲', category: 'SAT' },
    { id: 'sat-80', word: 'Resource', definition: 'useful thing', pronunciation: '/ˈriːsɔːrs/', exampleSentence: 'Natural resource.', imageEmoji: '💧', category: 'SAT' },
    { id: 'sat-81', word: 'Restrict', definition: 'limit', pronunciation: '/rɪˈstrɪkt/', exampleSentence: 'Restrict access.', imageEmoji: '🚧', category: 'SAT' },
    { id: 'sat-82', word: 'Scale', definition: 'size or level', pronunciation: '/skeɪl/', exampleSentence: 'Large scale.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-83', word: 'Sequence', definition: 'order', pronunciation: '/ˈsiːkwəns/', exampleSentence: 'Number sequence.', imageEmoji: '🔢', category: 'SAT' },
    { id: 'sat-84', word: 'Shift', definition: 'change', pronunciation: '/ʃɪft/', exampleSentence: 'Night shift.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-85', word: 'Statistics', definition: 'number facts', pronunciation: '/stəˈtɪstɪks/', exampleSentence: 'Study statistics.', imageEmoji: '📊', category: 'SAT' },
    { id: 'sat-86', word: 'Substitute', definition: 'replace', pronunciation: '/ˈsʌbstɪtuːt/', exampleSentence: 'Substitute teacher.', imageEmoji: '🔁', category: 'SAT' },
    { id: 'sat-87', word: 'Temporary', definition: 'not lasting long', pronunciation: '/ˈtempəreri/', exampleSentence: 'Temporary job.', imageEmoji: '⏳', category: 'SAT' },
    { id: 'sat-88', word: 'Valid', definition: 'correct', pronunciation: '/ˈvælɪd/', exampleSentence: 'Valid point.', imageEmoji: '✅', category: 'SAT' },
    { id: 'sat-89', word: 'Widespread', definition: 'happening many places', pronunciation: '/ˈwaɪdspred/', exampleSentence: 'Widespread panic.', imageEmoji: '🌍', category: 'SAT' },
    { id: 'sat-90', word: 'Accurate', definition: 'correct', pronunciation: '/ˈækjərət/', exampleSentence: 'Accurate clock.', imageEmoji: '🎯', category: 'SAT' },
    { id: 'sat-91', word: 'Approximate', definition: 'close but not exact', pronunciation: '/əˈprɑːksɪmət/', exampleSentence: 'Approximate cost.', imageEmoji: '📏', category: 'SAT' },
    { id: 'sat-92', word: 'Authority', definition: 'power', pronunciation: '/əˈθɔːrəti/', exampleSentence: 'Person in authority.', imageEmoji: '👮', category: 'SAT' },
    { id: 'sat-93', word: 'Civil', definition: 'about society', pronunciation: '/ˈsɪvl/', exampleSentence: 'Civil rights.', imageEmoji: '🏛️', category: 'SAT' },
    { id: 'sat-94', word: 'Compile', definition: 'collect', pronunciation: '/kəmˈpaɪl/', exampleSentence: 'Compile items.', imageEmoji: '📚', category: 'SAT' },
    { id: 'sat-95', word: 'Consent', definition: 'permission', pronunciation: '/kənˈsent/', exampleSentence: 'Give consent.', imageEmoji: '✍️', category: 'SAT' },
    { id: 'sat-96', word: 'Cooperate', definition: 'work together', pronunciation: '/koʊˈɑːpəreɪt/', exampleSentence: 'We must cooperate.', imageEmoji: '🤝', category: 'SAT' },
    { id: 'sat-97', word: 'Detect', definition: 'find', pronunciation: '/dɪˈtekt/', exampleSentence: 'Detect smoke.', imageEmoji: '🕵️', category: 'SAT' },
    { id: 'sat-98', word: 'Document', definition: 'written record', pronunciation: '/ˈdɑːkjumənt/', exampleSentence: 'Legal document.', imageEmoji: '📄', category: 'SAT' },
    { id: 'sat-99', word: 'Eliminate', definition: 'remove', pronunciation: '/ɪˈlɪmɪneɪt/', exampleSentence: 'Eliminate errors.', imageEmoji: '🗑️', category: 'SAT' },
    { id: 'sat-100', word: 'Emerging', definition: 'starting to appear', pronunciation: '/ɪˈmɜːrdʒɪŋ/', exampleSentence: 'Emerging artist.', imageEmoji: '🌱', category: 'SAT' },

    // 101-120
    { id: 'sat-101', word: 'Ethical', definition: 'morally right', pronunciation: '/ˈeθɪkl/', exampleSentence: 'Ethical choice.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-102', word: 'Foundation', definition: 'base', pronunciation: '/faʊnˈdeɪʃn/', exampleSentence: 'Strong foundation.', imageEmoji: '🧱', category: 'SAT' },
    { id: 'sat-103', word: 'Guideline', definition: 'rule', pronunciation: '/ˈɡaɪdlaɪn/', exampleSentence: 'Follow the guideline.', imageEmoji: '📏', category: 'SAT' },
    { id: 'sat-104', word: 'Hierarchy', definition: 'order of importance', pronunciation: '/ˈhaɪərɑːrki/', exampleSentence: 'Company hierarchy.', imageEmoji: '🤴', category: 'SAT' },
    { id: 'sat-105', word: 'Internal', definition: 'inside', pronunciation: '/ɪnˈtɜːrnl/', exampleSentence: 'Internal injury.', imageEmoji: '🏠', category: 'SAT' },
    { id: 'sat-106', word: 'Isolate', definition: 'separate', pronunciation: '/ˈaɪsəleɪt/', exampleSentence: 'Isolate the sick.', imageEmoji: '😷', category: 'SAT' },
    { id: 'sat-107', word: 'Justify', definition: 'explain why right', pronunciation: '/ˈdʒʌstɪfaɪ/', exampleSentence: 'Justify the cost.', imageEmoji: '🤔', category: 'SAT' },
    { id: 'sat-108', word: 'Label', definition: 'name', pronunciation: '/ˈleɪbl/', exampleSentence: 'Read the label.', imageEmoji: '🏷️', category: 'SAT' },
    { id: 'sat-109', word: 'Mechanism', definition: 'how something works', pronunciation: '/ˈmekənɪzm/', exampleSentence: 'Clock mechanism.', imageEmoji: '⚙️', category: 'SAT' },
    { id: 'sat-110', word: 'Network', definition: 'connected group', pronunciation: '/ˈnetwɜːrk/', exampleSentence: 'Computer network.', imageEmoji: '🌐', category: 'SAT' },
    { id: 'sat-111', word: 'Notion', definition: 'idea', pronunciation: '/ˈnoʊʃn/', exampleSentence: 'Silly notion.', imageEmoji: '💡', category: 'SAT' },
    { id: 'sat-112', word: 'Parameter', definition: 'limit', pronunciation: '/pəˈræmɪtər/', exampleSentence: 'Set parameters.', imageEmoji: '📐', category: 'SAT' },
    { id: 'sat-113', word: 'Perceive', definition: 'notice', pronunciation: '/pərˈsiːv/', exampleSentence: 'Perceive danger.', imageEmoji: '👀', category: 'SAT' },
    { id: 'sat-114', word: 'Preliminary', definition: 'early', pronunciation: '/prɪˈlɪmɪneri/', exampleSentence: 'Preliminary round.', imageEmoji: '🏁', category: 'SAT' },
    { id: 'sat-115', word: 'Proportion', definition: 'part of whole', pronunciation: '/prəˈpɔːrʃn/', exampleSentence: 'Large proportion.', imageEmoji: '🍰', category: 'SAT' },
    { id: 'sat-116', word: 'Reform', definition: 'improve', pronunciation: '/rɪˈfɔːrm/', exampleSentence: 'Tax reform.', imageEmoji: '🔨', category: 'SAT' },
    { id: 'sat-117', word: 'Regulate', definition: 'control', pronunciation: '/ˈreɡjuleɪt/', exampleSentence: 'Regulate heat.', imageEmoji: '🎛️', category: 'SAT' },
    { id: 'sat-118', word: 'Reinforce', definition: 'make stronger', pronunciation: '/ˌriːɪnˈfɔːrs/', exampleSentence: 'Reinforce wall.', imageEmoji: '🧱', category: 'SAT' },
    { id: 'sat-119', word: 'Scenario', definition: 'situation', pronunciation: '/səˈnerioʊ/', exampleSentence: 'Worst case scenario.', imageEmoji: '🎬', category: 'SAT' },
    { id: 'sat-120', word: 'Sector', definition: 'part of society', pronunciation: '/ˈsektər/', exampleSentence: 'Private sector.', imageEmoji: '🏢', category: 'SAT' },

    // 121-189
    { id: 'sat-121', word: 'Simultaneous', definition: 'at same time', pronunciation: '/ˌsaɪmlˈteɪniəs/', exampleSentence: 'Simultaneous action.', imageEmoji: '🕒', category: 'SAT' },
    { id: 'sat-122', word: 'Stance', definition: 'opinion', pronunciation: '/stæns/', exampleSentence: 'Take a stance.', imageEmoji: '🦶', category: 'SAT' },
    { id: 'sat-123', word: 'Stimulate', definition: 'encourage', pronunciation: '/ˈstɪmjuleɪt/', exampleSentence: 'Stimulate growth.', imageEmoji: '🌱', category: 'SAT' },
    { id: 'sat-124', word: 'Subsequent', definition: 'coming after', pronunciation: '/ˈsʌbsɪkwənt/', exampleSentence: 'Subsequent events.', imageEmoji: '⏭️', category: 'SAT' },
    { id: 'sat-125', word: 'Sufficient', definition: 'enough', pronunciation: '/səˈfɪʃnt/', exampleSentence: 'Sufficient food.', imageEmoji: '🍲', category: 'SAT' },
    { id: 'sat-126', word: 'Target', definition: 'goal', pronunciation: '/ˈtɑːrɡɪt/', exampleSentence: 'Hit the target.', imageEmoji: '🎯', category: 'SAT' },
    { id: 'sat-127', word: 'Tendency', definition: 'habit', pronunciation: '/ˈtendənsi/', exampleSentence: 'A tendency to forget.', imageEmoji: '🤔', category: 'SAT' },
    { id: 'sat-128', word: 'Underlying', definition: 'hidden but important', pronunciation: '/ˌʌndərˈlaɪɪŋ/', exampleSentence: 'Underlying cause.', imageEmoji: '👇', category: 'SAT' },
    { id: 'sat-129', word: 'Uniform', definition: 'the same', pronunciation: '/ˈjuːnɪfɔːrm/', exampleSentence: 'Uniform size.', imageEmoji: '👮', category: 'SAT' },
    { id: 'sat-130', word: 'Utilize', definition: 'use', pronunciation: '/ˈjuːtəlaɪz/', exampleSentence: 'Utilize tools.', imageEmoji: '🛠️', category: 'SAT' },
    { id: 'sat-131', word: 'Verify', definition: 'check', pronunciation: '/ˈverɪfaɪ/', exampleSentence: 'Verify the truth.', imageEmoji: '✅', category: 'SAT' },
    { id: 'sat-132', word: 'Violate', definition: 'break rule', pronunciation: '/ˈvaɪəleɪt/', exampleSentence: 'Violate the law.', imageEmoji: '🚫', category: 'SAT' },
    { id: 'sat-133', word: 'Welfare', definition: 'well-being', pronunciation: '/ˈwelfer/', exampleSentence: 'Public welfare.', imageEmoji: '🏥', category: 'SAT' },
    { id: 'sat-134', word: 'Abstract', definition: 'hard to see', pronunciation: '/ˈæbstrækt/', exampleSentence: 'Abstract concept.', imageEmoji: '🎨', category: 'SAT' },
    { id: 'sat-135', word: 'Aggregate', definition: 'total', pronunciation: '/ˈæɡrɪɡət/', exampleSentence: 'Aggregate score.', imageEmoji: '∑', category: 'SAT' },
    { id: 'sat-136', word: 'Ambiguous', definition: 'unclear', pronunciation: '/æmˈbɪɡjuəs/', exampleSentence: 'Ambiguous sign.', imageEmoji: '❓', category: 'SAT' },
    { id: 'sat-137', word: 'Allocate', definition: 'give out', pronunciation: '/ˈæləkeɪt/', exampleSentence: 'Allocate funds.', imageEmoji: '💸', category: 'SAT' },
    { id: 'sat-138', word: 'Coherent', definition: 'makes sense', pronunciation: '/koʊˈhɪrənt/', exampleSentence: 'Coherent speech.', imageEmoji: '🗣️', category: 'SAT' },
    { id: 'sat-139', word: 'Constraint', definition: 'limit', pronunciation: '/kənˈstreɪnt/', exampleSentence: 'Budget constraint.', imageEmoji: '⛓️', category: 'SAT' },
    { id: 'sat-140', word: 'Conventional', definition: 'usual', pronunciation: '/kənˈvenʃənl/', exampleSentence: 'Conventional wisdom.', imageEmoji: '🎩', category: 'SAT' },
    { id: 'sat-141', word: 'Correlation', definition: 'connection', pronunciation: '/ˌkɔːrəˈleɪʃn/', exampleSentence: 'Strong correlation.', imageEmoji: '🔗', category: 'SAT' },
    { id: 'sat-142', word: 'Domain', definition: 'area', pronunciation: '/doʊˈmeɪn/', exampleSentence: 'My domain.', imageEmoji: '🏰', category: 'SAT' },
    { id: 'sat-143', word: 'Equivalent', definition: 'equal', pronunciation: '/ɪˈkwɪvələnt/', exampleSentence: 'Equivalent value.', imageEmoji: '=', category: 'SAT' },
    { id: 'sat-144', word: 'Exhibit', definition: 'show', pronunciation: '/ɪɡˈzɪbɪt/', exampleSentence: 'Exhibit art.', imageEmoji: '🖼️', category: 'SAT' },
    { id: 'sat-145', word: 'External', definition: 'outside', pronunciation: '/ɪkˈstɜːrnl/', exampleSentence: 'External drive.', imageEmoji: '📤', category: 'SAT' },
    { id: 'sat-146', word: 'Finite', definition: 'having an end', pronunciation: '/ˈfaɪnaɪt/', exampleSentence: 'Finite supply.', imageEmoji: '⏳', category: 'SAT' },
    { id: 'sat-147', word: 'Implicit', definition: 'suggested', pronunciation: '/ɪmˈplɪsɪt/', exampleSentence: 'Implicit meaning.', imageEmoji: '😉', category: 'SAT' },
    { id: 'sat-148', word: 'Induce', definition: 'cause', pronunciation: '/ɪnˈduːs/', exampleSentence: 'Induce sleep.', imageEmoji: '😴', category: 'SAT' },
    { id: 'sat-149', word: 'Magnitude', definition: 'size', pronunciation: '/ˈmæɡnɪtuːd/', exampleSentence: 'Great magnitude.', imageEmoji: '📏', category: 'SAT' },
    { id: 'sat-150', word: 'Norm', definition: 'usual rule', pronunciation: '/nɔːrm/', exampleSentence: 'Social norm.', imageEmoji: '📋', category: 'SAT' },
    { id: 'sat-151', word: 'Offset', definition: 'balance', pronunciation: '/ˈɔːfset/', exampleSentence: 'Offset the cost.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-152', word: 'Paradigm', definition: 'model', pronunciation: '/ˈpærədaɪm/', exampleSentence: 'New paradigm.', imageEmoji: '🗺️', category: 'SAT' },
    { id: 'sat-153', word: 'Persistent', definition: 'not giving up', pronunciation: '/pərˈsɪstənt/', exampleSentence: 'Persistent rain.', imageEmoji: '🌧️', category: 'SAT' },
    { id: 'sat-154', word: 'Prevalent', definition: 'common', pronunciation: '/ˈprevələnt/', exampleSentence: 'Prevalent view.', imageEmoji: '👀', category: 'SAT' },
    { id: 'sat-155', word: 'Prospective', definition: 'future', pronunciation: '/prəˈspektɪv/', exampleSentence: 'Prospective buyer.', imageEmoji: '🔮', category: 'SAT' },
    { id: 'sat-156', word: 'Qualitative', definition: 'about qualities', pronunciation: '/ˈkwɑːlɪteɪtɪv/', exampleSentence: 'Qualitative data.', imageEmoji: '📝', category: 'SAT' },
    { id: 'sat-157', word: 'Quantitative', definition: 'about numbers', pronunciation: '/ˈkwɑːntɪteɪtɪv/', exampleSentence: 'Quantitative data.', imageEmoji: '🔢', category: 'SAT' },
    { id: 'sat-158', word: 'Robust', definition: 'strong', pronunciation: '/roʊˈbʌst/', exampleSentence: 'Robust flavor.', imageEmoji: '💪', category: 'SAT' },
    { id: 'sat-159', word: 'Subtle', definition: 'hard to notice', pronunciation: '/ˈsʌtl/', exampleSentence: 'Subtle change.', imageEmoji: '🕵️', category: 'SAT' },
    { id: 'sat-160', word: 'Synthesize', definition: 'combine ideas', pronunciation: '/ˈsɪnθəsaɪz/', exampleSentence: 'Synthesize info.', imageEmoji: '🧪', category: 'SAT' },
    { id: 'sat-161', word: 'Threshold', definition: 'starting point', pronunciation: '/ˈθreʃhoʊld/', exampleSentence: 'Pain threshold.', imageEmoji: '🚪', category: 'SAT' },
    { id: 'sat-162', word: 'Ubiquitous', definition: 'everywhere', pronunciation: '/juːˈbɪkwɪtəs/', exampleSentence: 'Ubiquitous phones.', imageEmoji: '📱', category: 'SAT' },
    { id: 'sat-163', word: 'Viable', definition: 'able to work', pronunciation: '/ˈvaɪəbl/', exampleSentence: 'Viable plan.', imageEmoji: '🌱', category: 'SAT' },
    { id: 'sat-164', word: 'Voluntary', definition: 'by choice', pronunciation: '/ˈvɑːlənteri/', exampleSentence: 'Voluntary work.', imageEmoji: '🙋', category: 'SAT' },
    { id: 'sat-165', word: 'Compatible', definition: 'work together', pronunciation: '/kəmˈpætəbl/', exampleSentence: 'Compatible parts.', imageEmoji: '🧩', category: 'SAT' },
    { id: 'sat-166', word: 'Concurrent', definition: 'at same time', pronunciation: '/kənˈkɜːrənt/', exampleSentence: 'Concurrent events.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-167', word: 'Controversy', definition: 'big disagreement', pronunciation: '/ˈkɑːntrəvɜːrsi/', exampleSentence: 'Public controversy.', imageEmoji: '🗣️', category: 'SAT' },
    { id: 'sat-168', word: 'Equilibrium', definition: 'balance', pronunciation: '/ˌiːkwɪˈlɪbriəm/', exampleSentence: 'Market equilibrium.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-169', word: 'Explicit', definition: 'clearly said', pronunciation: '/ɪkˈsplɪsɪt/', exampleSentence: 'Explicit instruction.', imageEmoji: '📢', category: 'SAT' },
    { id: 'sat-170', word: 'Feasible', definition: 'possible', pronunciation: '/ˈfiːzəbl/', exampleSentence: 'Is it feasible?', imageEmoji: '👍', category: 'SAT' },
    { id: 'sat-171', word: 'Marginal', definition: 'small', pronunciation: '/ˈmɑːrdʒɪnl/', exampleSentence: 'Marginal cost.', imageEmoji: '🤏', category: 'SAT' },
    { id: 'sat-172', word: 'Moderate', definition: 'not too much', pronunciation: '/ˈmɑːdərət/', exampleSentence: 'Moderate amount.', imageEmoji: '🌤️', category: 'SAT' },
    { id: 'sat-173', word: 'Negligible', definition: 'very small', pronunciation: '/ˈneɡlɪdʒəbl/', exampleSentence: 'Negligible effect.', imageEmoji: '🐜', category: 'SAT' },
    { id: 'sat-174', word: 'Optimal', definition: 'best', pronunciation: '/ˈɑːptɪml/', exampleSentence: 'Optimal solution.', imageEmoji: '🌟', category: 'SAT' },
    { id: 'sat-175', word: 'Precede', definition: 'come before', pronunciation: '/prɪˈsiːd/', exampleSentence: 'A precedes B.', imageEmoji: '⬅️', category: 'SAT' },
    { id: 'sat-176', word: 'Sole', definition: 'only', pronunciation: '/soʊl/', exampleSentence: 'Sole survivor.', imageEmoji: '☝️', category: 'SAT' },
    { id: 'sat-177', word: 'Sustainability', definition: 'lasting long time', pronunciation: '/səˌsteɪnəˈbɪləti/', exampleSentence: 'Sustainability goal.', imageEmoji: '🌍', category: 'SAT' },
    { id: 'sat-178', word: 'Bias', definition: 'unfair opinion', pronunciation: '/ˈbaɪəs/', exampleSentence: 'Show bias.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-179', word: 'Category', definition: 'group', pronunciation: '/ˈkætəɡɔːri/', exampleSentence: 'Food category.', imageEmoji: '🏷️', category: 'SAT' },
    { id: 'sat-180', word: 'Circumstance', definition: 'situation', pronunciation: '/ˈsɜːrkəmstæns/', exampleSentence: 'Special circumstance.', imageEmoji: '🚩', category: 'SAT' },
    { id: 'sat-181', word: 'Complex', definition: 'complicated', pronunciation: '/kəmˈpleks/', exampleSentence: 'Complex puzzle.', imageEmoji: '🧩', category: 'SAT' },
    { id: 'sat-182', word: 'Conflict', definition: 'disagreement', pronunciation: '/ˈkɑːnflɪkt/', exampleSentence: 'Conflict of interest.', imageEmoji: '⚔️', category: 'SAT' },
    { id: 'sat-183', word: 'Contemporary', definition: 'modern', pronunciation: '/kənˈtempəreri/', exampleSentence: 'Contemporary art.', imageEmoji: '🖼️', category: 'SAT' },
    { id: 'sat-184', word: 'Criterion', definition: 'rule for judging', pronunciation: '/kraɪˈtɪriən/', exampleSentence: 'Selection criterion.', imageEmoji: '📏', category: 'SAT' },
    { id: 'sat-185', word: 'Data', definition: 'information', pronunciation: '/ˈdeɪtə/', exampleSentence: 'Analyze data.', imageEmoji: '📊', category: 'SAT' },
    { id: 'sat-186', word: 'Debate', definition: 'argument', pronunciation: '/dɪˈbeɪt/', exampleSentence: 'School debate.', imageEmoji: '🎙️', category: 'SAT' },
    { id: 'sat-187', word: 'Decade', definition: 'ten years', pronunciation: '/ˈdekeɪd/', exampleSentence: 'Past decade.', imageEmoji: '📅', category: 'SAT' },
    { id: 'sat-188', word: 'Distribution', definition: 'how spread out', pronunciation: '/ˌdɪstrɪˈbjuːʃn/', exampleSentence: 'Wealth distribution.', imageEmoji: '🌍', category: 'SAT' },
    { id: 'sat-189', word: 'Economy', definition: 'money system', pronunciation: '/ɪˈkɑːnəmi/', exampleSentence: 'Global economy.', imageEmoji: '💸', category: 'SAT' },

    // 190-250
    { id: 'sat-190', word: 'Environment', definition: 'surroundings', pronunciation: '/ɪnˈvaɪrənmənt/', exampleSentence: 'Protect the environment.', imageEmoji: '🌳', category: 'SAT' },
    { id: 'sat-191', word: 'Estimate', definition: 'smart guess', pronunciation: '/ˈestɪmət/', exampleSentence: 'Rough estimate.', imageEmoji: '🤔', category: 'SAT' },
    { id: 'sat-192', word: 'Expose', definition: 'show', pronunciation: '/ɪkˈspoʊz/', exampleSentence: 'Expose the truth.', imageEmoji: '📸', category: 'SAT' },
    { id: 'sat-193', word: 'Feature', definition: 'important part', pronunciation: '/ˈfiːtʃər/', exampleSentence: 'Key feature.', imageEmoji: '⭐', category: 'SAT' },
    { id: 'sat-194', word: 'Flexible', definition: 'able to change', pronunciation: '/ˈfleksəbl/', exampleSentence: 'Flexible schedule.', imageEmoji: '🤸', category: 'SAT' },
    { id: 'sat-195', word: 'Global', definition: 'whole world', pronunciation: '/ˈɡloʊbl/', exampleSentence: 'Global warming.', imageEmoji: '🌍', category: 'SAT' },
    { id: 'sat-196', word: 'Hypothesis', definition: 'test idea', pronunciation: '/haɪˈpɑːθəsɪs/', exampleSentence: 'Scientific hypothesis.', imageEmoji: '🧪', category: 'SAT' },
    { id: 'sat-197', word: 'Immigrate', definition: 'move countries', pronunciation: '/ˈɪmɪɡreɪt/', exampleSentence: 'Immigrate to US.', imageEmoji: '✈️', category: 'SAT' },
    { id: 'sat-198', word: 'Journal', definition: 'written record', pronunciation: '/ˈdʒɜːrnl/', exampleSentence: 'Keep a journal.', imageEmoji: '📓', category: 'SAT' },
    { id: 'sat-199', word: 'Labor', definition: 'work', pronunciation: '/ˈleɪbər/', exampleSentence: 'Hard labor.', imageEmoji: '👷', category: 'SAT' },
    { id: 'sat-200', word: 'Stability', definition: 'staying steady', pronunciation: '/stəˈbɪləti/', exampleSentence: 'Political stability.', imageEmoji: '🏛️', category: 'SAT' },
    { id: 'sat-201', word: 'Annual', definition: 'yearly', pronunciation: '/ˈænjuəl/', exampleSentence: 'Annual meeting.', imageEmoji: '📅', category: 'SAT' },
    { id: 'sat-202', word: 'Adjacent', definition: 'next to', pronunciation: '/əˈdʒeɪsnt/', exampleSentence: 'Adjacent room.', imageEmoji: '🏘️', category: 'SAT' },
    { id: 'sat-203', word: 'Domestic', definition: 'inside a country', pronunciation: '/dəˈmestɪk/', exampleSentence: 'Domestic flight.', imageEmoji: '🏠', category: 'SAT' },
    { id: 'sat-204', word: 'Display', definition: 'show', pronunciation: '/dɪˈspleɪ/', exampleSentence: 'Display art.', imageEmoji: '🖼️', category: 'SAT' },
    { id: 'sat-205', word: 'Withdraw', definition: 'pull back', pronunciation: '/wɪðˈdrɔː/', exampleSentence: 'Withdraw money.', imageEmoji: '🏧', category: 'SAT' },
    { id: 'sat-206', word: 'Visible', definition: 'can be seen', pronunciation: '/ˈvɪzəbl/', exampleSentence: 'Visible stars.', imageEmoji: '👁️', category: 'SAT' },
    { id: 'sat-207', word: 'Volume', definition: 'amount', pronunciation: '/ˈvɑːljuːm/', exampleSentence: 'High volume.', imageEmoji: '🔊', category: 'SAT' },
    { id: 'sat-208', word: 'Brief', definition: 'short', pronunciation: '/briːf/', exampleSentence: 'Brief chat.', imageEmoji: '⏱️', category: 'SAT' },
    { id: 'sat-209', word: 'Capable', definition: 'able to do', pronunciation: '/ˈkeɪpəbl/', exampleSentence: 'Capable student.', imageEmoji: '💪', category: 'SAT' },
    { id: 'sat-210', word: 'Challenge', definition: 'something hard', pronunciation: '/ˈtʃælɪndʒ/', exampleSentence: 'Face a challenge.', imageEmoji: '🏔️', category: 'SAT' },
    { id: 'sat-211', word: 'Combine', definition: 'put together', pronunciation: '/kəmˈbaɪn/', exampleSentence: 'Combine ingredients.', imageEmoji: '🥣', category: 'SAT' },
    { id: 'sat-212', word: 'Common', definition: 'happens a lot', pronunciation: '/ˈkɑːmən/', exampleSentence: 'Common cold.', imageEmoji: '🤧', category: 'SAT' },
    { id: 'sat-213', word: 'Control', definition: 'manage', pronunciation: '/kənˈtroʊl/', exampleSentence: 'Control the car.', imageEmoji: '🎮', category: 'SAT' },
    { id: 'sat-214', word: 'Create', definition: 'make something new', pronunciation: '/kriˈeɪt/', exampleSentence: 'Create art.', imageEmoji: '🎨', category: 'SAT' },
    { id: 'sat-215', word: 'Define', definition: 'explain meaning', pronunciation: '/dɪˈfaɪn/', exampleSentence: 'Define the word.', imageEmoji: '📖', category: 'SAT' },
    { id: 'sat-216', word: 'Difference', definition: 'how things are not same', pronunciation: '/ˈdɪfrəns/', exampleSentence: 'Spot the difference.', imageEmoji: '🆚', category: 'SAT' },
    { id: 'sat-217', word: 'Effect', definition: 'result', pronunciation: '/ɪˈfekt/', exampleSentence: 'Cause and effect.', imageEmoji: '⚡', category: 'SAT' },
    { id: 'sat-218', word: 'Emphasize', definition: 'show importance', pronunciation: '/ˈemfəsaɪz/', exampleSentence: 'Emphasize this.', imageEmoji: '‼️', category: 'SAT' },
    { id: 'sat-219', word: 'Focus', definition: 'pay attention', pronunciation: '/ˈfoʊkəs/', exampleSentence: 'Focus on work.', imageEmoji: '🧘', category: 'SAT' },
    { id: 'sat-220', word: 'Identify', definition: 'find or name', pronunciation: '/aɪˈdentɪfaɪ/', exampleSentence: 'Identify the person.', imageEmoji: '🆔', category: 'SAT' },
    { id: 'sat-221', word: 'Issue', definition: 'problem', pronunciation: '/ˈɪʃuː/', exampleSentence: 'Big issue.', imageEmoji: '⚠️', category: 'SAT' },
    { id: 'sat-222', word: 'Limit', definition: 'stop point', pronunciation: '/ˈlɪmɪt/', exampleSentence: 'No limit.', imageEmoji: '🛑', category: 'SAT' },
    { id: 'sat-223', word: 'Notice', definition: 'see', pronunciation: '/ˈnoʊtɪs/', exampleSentence: 'Did you notice?', imageEmoji: '👀', category: 'SAT' },
    { id: 'sat-224', word: 'Period', definition: 'time length', pronunciation: '/ˈpɪriəd/', exampleSentence: 'Short period.', imageEmoji: '⏳', category: 'SAT' },
    { id: 'sat-225', word: 'Provide', definition: 'give', pronunciation: '/prəˈvɑɪd/', exampleSentence: 'Provide food.', imageEmoji: '🤲', category: 'SAT' },
    { id: 'sat-226', word: 'React', definition: 'respond', pronunciation: '/riˈækt/', exampleSentence: 'React quickly.', imageEmoji: '😲', category: 'SAT' },
    { id: 'sat-227', word: 'Relate', definition: 'connect', pronunciation: '/rɪˈleɪt/', exampleSentence: 'Relate the story.', imageEmoji: '🔗', category: 'SAT' },
    { id: 'sat-228', word: 'Result', definition: 'final outcome', pronunciation: '/rɪˈzʌlt/', exampleSentence: 'Good result.', imageEmoji: '🏆', category: 'SAT' },
    { id: 'sat-229', word: 'Section', definition: 'part of something', pronunciation: '/ˈsekʃn/', exampleSentence: 'Section one.', imageEmoji: '🍰', category: 'SAT' },
    { id: 'sat-230', word: 'Similar', definition: 'almost the same', pronunciation: '/ˈsɪmɪlər/', exampleSentence: 'Similar looks.', imageEmoji: '👯', category: 'SAT' },
    { id: 'sat-231', word: 'Support', definition: 'help', pronunciation: '/səˈpɔːrt/', exampleSentence: 'Support your team.', imageEmoji: '🤝', category: 'SAT' },
    { id: 'sat-232', word: 'Symbol', definition: 'sign that means something', pronunciation: '/ˈsɪmbl/', exampleSentence: 'Peace symbol.', imageEmoji: '☮️', category: 'SAT' },
    { id: 'sat-233', word: 'Transition', definition: 'change', pronunciation: '/trænˈzɪʃn/', exampleSentence: 'Make a transition.', imageEmoji: '🌉', category: 'SAT' },
    { id: 'sat-234', word: 'Accurate', definition: 'correct', pronunciation: '/ˈækjərət/', exampleSentence: 'Accurate news.', imageEmoji: '✅', category: 'SAT' },
    { id: 'sat-235', word: 'Alternative', definition: 'another choice', pronunciation: '/ɔːlˈtɜːrnətɪv/', exampleSentence: 'Alternative route.', imageEmoji: '🛤️', category: 'SAT' },
    { id: 'sat-236', word: 'Assistance', definition: 'help', pronunciation: '/əˈsɪstəns/', exampleSentence: 'Need assistance?', imageEmoji: '🆘', category: 'SAT' },
    { id: 'sat-237', word: 'Bias', definition: 'unfair thinking', pronunciation: '/ˈbaɪəs/', exampleSentence: 'Personal bias.', imageEmoji: '🧠', category: 'SAT' },
    { id: 'sat-238', word: 'Category', definition: 'group', pronunciation: '/ˈkætəɡɔːri/', exampleSentence: 'Choose category.', imageEmoji: '📂', category: 'SAT' },
    { id: 'sat-239', word: 'Circumstance', definition: 'situation', pronunciation: '/ˈsɜːrkəmstæns/', exampleSentence: 'Bad circumstance.', imageEmoji: '🌩️', category: 'SAT' },
    { id: 'sat-240', word: 'Conflict', definition: 'disagreement', pronunciation: '/ˈkɑːnflɪkt/', exampleSentence: 'Avoid conflict.', imageEmoji: '🥊', category: 'SAT' },
    { id: 'sat-241', word: 'Definite', definition: 'clear', pronunciation: '/ˈdefɪnət/', exampleSentence: 'Definite answer.', imageEmoji: '👍', category: 'SAT' },
    { id: 'sat-242', word: 'Element', definition: 'basic part', pronunciation: '/ˈelɪmənt/', exampleSentence: 'Key element.', imageEmoji: '⚛️', category: 'SAT' },
    { id: 'sat-243', word: 'Eventually', definition: 'later', pronunciation: '/ɪˈventʃuəli/', exampleSentence: 'Eventually arrived.', imageEmoji: '🏁', category: 'SAT' },
    { id: 'sat-244', word: 'Expose', definition: 'show', pronunciation: '/ɪkˈspoʊz/', exampleSentence: 'Expose skin.', imageEmoji: '☀️', category: 'SAT' },
    { id: 'sat-245', word: 'Feature', definition: 'important part', pronunciation: '/ˈfiːtʃər/', exampleSentence: 'Special feature.', imageEmoji: '✨', category: 'SAT' },
    { id: 'sat-246', word: 'Flexible', definition: 'can change', pronunciation: '/ˈfleksəbl/', exampleSentence: 'Flexible tubing.', imageEmoji: '🐍', category: 'SAT' },
    { id: 'sat-247', word: 'Global', definition: 'worldwide', pronunciation: '/ˈɡloʊbl/', exampleSentence: 'Global trade.', imageEmoji: '🚢', category: 'SAT' },
    { id: 'sat-248', word: 'Initial', definition: 'first', pronunciation: '/ɪˈnɪʃl/', exampleSentence: 'Initial tests.', imageEmoji: '1️⃣', category: 'SAT' },
    { id: 'sat-249', word: 'Instance', definition: 'example', pronunciation: '/ˈɪnstəns/', exampleSentence: 'Single instance.', imageEmoji: '👆', category: 'SAT' },
    { id: 'sat-250', word: 'Interaction', definition: 'working together', pronunciation: '/ˌɪntərˈækʃn/', exampleSentence: 'Interaction design.', imageEmoji: '🖱️', category: 'SAT' },
    { id: 'sat-251', word: 'Journal', definition: 'written record', pronunciation: '/ˈdʒɜːrnl/', exampleSentence: 'Keep a journal.', imageEmoji: '📓', category: 'SAT' },
    { id: 'sat-252', word: 'Layer', definition: 'level', pronunciation: '/ˈleɪər/', exampleSentence: 'Layer of cake.', imageEmoji: '🍰', category: 'SAT' },
    { id: 'sat-253', word: 'Locate', definition: 'find', pronunciation: '/ˈloʊkeɪt/', exampleSentence: 'Locate the map.', imageEmoji: '📍', category: 'SAT' },
    { id: 'sat-254', word: 'Majority', definition: 'more than half', pronunciation: '/məˈdʒɔːrəti/', exampleSentence: 'The majority voted.', imageEmoji: '✋', category: 'SAT' },
    { id: 'sat-255', word: 'Maximum', definition: 'most', pronunciation: '/ˈmæksɪməm/', exampleSentence: 'Maximum speed.', imageEmoji: '🔝', category: 'SAT' },
    { id: 'sat-256', word: 'Minimum', definition: 'least', pronunciation: '/ˈmɪnɪməm/', exampleSentence: 'Minimum wage.', imageEmoji: '⬇️', category: 'SAT' },
    { id: 'sat-257', word: 'Neutral', definition: 'not choosing sides', pronunciation: '/ˈnuːtrəl/', exampleSentence: 'Stay neutral.', imageEmoji: '😐', category: 'SAT' },
    { id: 'sat-258', word: 'Objective', definition: 'goal', pronunciation: '/əbˈdʒektɪv/', exampleSentence: 'Main objective.', imageEmoji: '🎯', category: 'SAT' },
    { id: 'sat-259', word: 'Oppose', definition: 'disagree', pronunciation: '/əˈpoʊz/', exampleSentence: 'Oppose the law.', imageEmoji: '🛑', category: 'SAT' },
    { id: 'sat-260', word: 'Outcome', definition: 'result', pronunciation: '/ˈaʊtkʌm/', exampleSentence: 'Good outcome.', imageEmoji: '🏁', category: 'SAT' },
    { id: 'sat-261', word: 'Primary', definition: 'main', pronunciation: '/ˈpraɪmeri/', exampleSentence: 'Primary cause.', imageEmoji: '☝️', category: 'SAT' },
    { id: 'sat-262', word: 'Prior', definition: 'earlier', pronunciation: '/ˈpraɪər/', exampleSentence: 'Prior engagement.', imageEmoji: '⏮️', category: 'SAT' },
    { id: 'sat-263', word: 'Publish', definition: 'share writing', pronunciation: '/ˈpʌblɪʃ/', exampleSentence: 'Publish a book.', imageEmoji: '📰', category: 'SAT' },
    { id: 'sat-264', word: 'Recover', definition: 'get back', pronunciation: '/rɪˈkʌvər/', exampleSentence: 'Recover files.', imageEmoji: '🩹', category: 'SAT' },
    { id: 'sat-265', word: 'Restrict', definition: 'limit', pronunciation: '/rɪˈstrɪkt/', exampleSentence: 'Restrict access.', imageEmoji: '🚧', category: 'SAT' },
    { id: 'sat-266', word: 'Scale', definition: 'size', pronunciation: '/skeɪl/', exampleSentence: 'Large scale.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-267', word: 'Shift', definition: 'change', pronunciation: '/ʃɪft/', exampleSentence: 'Night shift.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-268', word: 'Summary', definition: 'short version', pronunciation: '/ˈsʌməri/', exampleSentence: 'Read the summary.', imageEmoji: '📝', category: 'SAT' },
    { id: 'sat-269', word: 'Temporary', definition: 'not long', pronunciation: '/ˈtempəreri/', exampleSentence: 'Temporary job.', imageEmoji: '⏳', category: 'SAT' },
    { id: 'sat-270', word: 'Valid', definition: 'correct', pronunciation: '/ˈvælɪd/', exampleSentence: 'Valid point.', imageEmoji: '✅', category: 'SAT' },
    { id: 'sat-271', word: 'Widespread', definition: 'many places', pronunciation: '/ˈwaɪdspred/', exampleSentence: 'Widespread panic.', imageEmoji: '🌍', category: 'SAT' },
    { id: 'sat-272', word: 'Authority', definition: 'power', pronunciation: '/əˈθɔːrəti/', exampleSentence: 'Person in authority.', imageEmoji: '👮', category: 'SAT' },
    { id: 'sat-273', word: 'Civil', definition: 'about society', pronunciation: '/ˈsɪvl/', exampleSentence: 'Civil rights.', imageEmoji: '🏛️', category: 'SAT' },
    { id: 'sat-274', word: 'Compile', definition: 'gather', pronunciation: '/kəmˈpaɪl/', exampleSentence: 'Compile items.', imageEmoji: '📚', category: 'SAT' },
    { id: 'sat-275', word: 'Consent', definition: 'permission', pronunciation: '/kənˈsent/', exampleSentence: 'Give consent.', imageEmoji: '✍️', category: 'SAT' },
    { id: 'sat-276', word: 'Cooperate', definition: 'work together', pronunciation: '/koʊˈɑːpəreɪt/', exampleSentence: 'We must cooperate.', imageEmoji: '🤝', category: 'SAT' },
    { id: 'sat-277', word: 'Detect', definition: 'find', pronunciation: '/dɪˈtekt/', exampleSentence: 'Detect smoke.', imageEmoji: '🕵️', category: 'SAT' },
    { id: 'sat-278', word: 'Eliminate', definition: 'remove', pronunciation: '/ɪˈlɪmɪneɪt/', exampleSentence: 'Eliminate errors.', imageEmoji: '🗑️', category: 'SAT' },
    { id: 'sat-279', word: 'Ethical', definition: 'morally right', pronunciation: '/ˈeθɪkl/', exampleSentence: 'Ethical choice.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-280', word: 'Federal', definition: 'national', pronunciation: '/ˈfedərəl/', exampleSentence: 'Federal law.', imageEmoji: '🏛️', category: 'SAT' },
    { id: 'sat-281', word: 'Foundation', definition: 'base', pronunciation: '/faʊnˈdeɪʃn/', exampleSentence: 'Strong foundation.', imageEmoji: '🧱', category: 'SAT' },
    { id: 'sat-282', word: 'Guideline', definition: 'rule', pronunciation: '/ˈɡaɪdlaɪn/', exampleSentence: 'Follow the guideline.', imageEmoji: '📏', category: 'SAT' },
    { id: 'sat-283', word: 'Hierarchy', definition: 'order of importance', pronunciation: '/ˈhaɪərɑːrki/', exampleSentence: 'Company hierarchy.', imageEmoji: '🤴', category: 'SAT' },
    { id: 'sat-284', word: 'Internal', definition: 'inside', pronunciation: '/ɪnˈtɜːrnl/', exampleSentence: 'Internal injury.', imageEmoji: '🏠', category: 'SAT' },
    { id: 'sat-285', word: 'Isolate', definition: 'separate', pronunciation: '/ˈaɪsəleɪt/', exampleSentence: 'Isolate the sick.', imageEmoji: '😷', category: 'SAT' },
    { id: 'sat-286', word: 'Justify', definition: 'explain why', pronunciation: '/ˈdʒʌstɪfaɪ/', exampleSentence: 'Justify the cost.', imageEmoji: '🤔', category: 'SAT' },
    { id: 'sat-287', word: 'Label', definition: 'name', pronunciation: '/ˈleɪbl/', exampleSentence: 'Read the label.', imageEmoji: '🏷️', category: 'SAT' },
    { id: 'sat-288', word: 'Mechanism', definition: 'how it works', pronunciation: '/ˈmekənɪzm/', exampleSentence: 'Clock mechanism.', imageEmoji: '⚙️', category: 'SAT' },
    { id: 'sat-289', word: 'Network', definition: 'connected group', pronunciation: '/ˈnetwɜːrk/', exampleSentence: 'Computer network.', imageEmoji: '🌐', category: 'SAT' },
    { id: 'sat-290', word: 'Notion', definition: 'idea', pronunciation: '/ˈnoʊʃn/', exampleSentence: 'Silly notion.', imageEmoji: '💡', category: 'SAT' },
    { id: 'sat-291', word: 'Parameter', definition: 'limit', pronunciation: '/pəˈræmɪtər/', exampleSentence: 'Set parameters.', imageEmoji: '📐', category: 'SAT' },
    { id: 'sat-292', word: 'Perceive', definition: 'notice', pronunciation: '/pərˈsiːv/', exampleSentence: 'Perceive danger.', imageEmoji: '👀', category: 'SAT' },
    { id: 'sat-293', word: 'Preliminary', definition: 'early', pronunciation: '/prɪˈlɪmɪneri/', exampleSentence: 'Preliminary round.', imageEmoji: '🏁', category: 'SAT' },
    { id: 'sat-294', word: 'Proportion', definition: 'part of whole', pronunciation: '/prəˈpɔːrʃn/', exampleSentence: 'Large proportion.', imageEmoji: '🍰', category: 'SAT' },
    { id: 'sat-295', word: 'Reform', definition: 'improve', pronunciation: '/rɪˈfɔːrm/', exampleSentence: 'Tax reform.', imageEmoji: '🔨', category: 'SAT' },
    { id: 'sat-296', word: 'Regulate', definition: 'control', pronunciation: '/ˈreɡjuleɪt/', exampleSentence: 'Regulate heat.', imageEmoji: '🎛️', category: 'SAT' },
    { id: 'sat-297', word: 'Reinforce', definition: 'strengthen', pronunciation: '/ˌriːɪnˈfɔːrs/', exampleSentence: 'Reinforce wall.', imageEmoji: '🧱', category: 'SAT' },
    { id: 'sat-298', word: 'Scenario', definition: 'situation', pronunciation: '/səˈnerioʊ/', exampleSentence: 'Worst case scenario.', imageEmoji: '🎬', category: 'SAT' },
    { id: 'sat-299', word: 'Sector', definition: 'part', pronunciation: '/ˈsektər/', exampleSentence: 'Private sector.', imageEmoji: '🏢', category: 'SAT' },
    { id: 'sat-300', word: 'Simultaneous', definition: 'same time', pronunciation: '/ˌsaɪmlˈteɪniəs/', exampleSentence: 'Simultaneous action.', imageEmoji: '🕒', category: 'SAT' },
    { id: 'sat-301', word: 'Stance', definition: 'opinion', pronunciation: '/stæns/', exampleSentence: 'Take a stance.', imageEmoji: '🦶', category: 'SAT' },
    { id: 'sat-302', word: 'Stimulate', definition: 'encourage', pronunciation: '/ˈstɪmjuleɪt/', exampleSentence: 'Stimulate growth.', imageEmoji: '🌱', category: 'SAT' },
    { id: 'sat-303', word: 'Subsequent', definition: 'after', pronunciation: '/ˈsʌbsɪkwənt/', exampleSentence: 'Subsequent events.', imageEmoji: '⏭️', category: 'SAT' },
    { id: 'sat-304', word: 'Sufficient', definition: 'enough', pronunciation: '/səˈfɪʃnt/', exampleSentence: 'Sufficient food.', imageEmoji: '🍲', category: 'SAT' },
    { id: 'sat-305', word: 'Target', definition: 'goal', pronunciation: '/ˈtɑːrɡɪt/', exampleSentence: 'Hit the target.', imageEmoji: '🎯', category: 'SAT' },
    { id: 'sat-306', word: 'Tendency', definition: 'habit', pronunciation: '/ˈtendənsi/', exampleSentence: 'A tendency to forget.', imageEmoji: '🤔', category: 'SAT' },
    { id: 'sat-307', word: 'Underlying', definition: 'hidden but important', pronunciation: '/ˌʌndərˈlaɪɪŋ/', exampleSentence: 'Underlying cause.', imageEmoji: '👇', category: 'SAT' },
    { id: 'sat-308', word: 'Uniform', definition: 'same', pronunciation: '/ˈjuːnɪfɔːrm/', exampleSentence: 'Uniform size.', imageEmoji: '👮', category: 'SAT' },
    { id: 'sat-309', word: 'Utilize', definition: 'use', pronunciation: '/ˈjuːtəlaɪz/', exampleSentence: 'Utilize tools.', imageEmoji: '🛠️', category: 'SAT' },
    { id: 'sat-310', word: 'Verify', definition: 'check', pronunciation: '/ˈverɪfaɪ/', exampleSentence: 'Verify the truth.', imageEmoji: '✅', category: 'SAT' },
    { id: 'sat-311', word: 'Violate', definition: 'break rule', pronunciation: '/ˈvaɪəleɪt/', exampleSentence: 'Violate the law.', imageEmoji: '🚫', category: 'SAT' },
    { id: 'sat-312', word: 'Welfare', definition: 'well-being', pronunciation: '/ˈwelfer/', exampleSentence: 'Public welfare.', imageEmoji: '🏥', category: 'SAT' },
    { id: 'sat-313', word: 'Abstract', definition: 'hard to see', pronunciation: '/ˈæbstrækt/', exampleSentence: 'Abstract concept.', imageEmoji: '🎨', category: 'SAT' },
    { id: 'sat-314', word: 'Aggregate', definition: 'total', pronunciation: '/ˈæɡrɪɡət/', exampleSentence: 'Aggregate score.', imageEmoji: '∑', category: 'SAT' },
    { id: 'sat-315', word: 'Ambiguous', definition: 'unclear', pronunciation: '/æmˈbɪɡjuəs/', exampleSentence: 'Ambiguous sign.', imageEmoji: '❓', category: 'SAT' },
    { id: 'sat-316', word: 'Allocate', definition: 'give out', pronunciation: '/ˈæləkeɪt/', exampleSentence: 'Allocate funds.', imageEmoji: '💸', category: 'SAT' },
    { id: 'sat-317', word: 'Coherent', definition: 'makes sense', pronunciation: '/koʊˈhɪrənt/', exampleSentence: 'Coherent speech.', imageEmoji: '🗣️', category: 'SAT' },
    { id: 'sat-318', word: 'Commodity', definition: 'thing sold', pronunciation: '/kəˈmɑːdəti/', exampleSentence: 'Valuable commodity.', imageEmoji: '📦', category: 'SAT' },
    { id: 'sat-319', word: 'Constraint', definition: 'limit', pronunciation: '/kənˈstreɪnt/', exampleSentence: 'Budget constraint.', imageEmoji: '⛓️', category: 'SAT' },
    { id: 'sat-320', word: 'Conventional', definition: 'usual', pronunciation: '/kənˈvenʃənl/', exampleSentence: 'Conventional wisdom.', imageEmoji: '🎩', category: 'SAT' },
    { id: 'sat-321', word: 'Correlation', definition: 'connection', pronunciation: '/ˌkɔːrəˈleɪʃn/', exampleSentence: 'Strong correlation.', imageEmoji: '🔗', category: 'SAT' },
    { id: 'sat-322', word: 'Domain', definition: 'area', pronunciation: '/doʊˈmeɪn/', exampleSentence: 'My domain.', imageEmoji: '🏰', category: 'SAT' },
    { id: 'sat-323', word: 'Equivalent', definition: 'equal', pronunciation: '/ɪˈkwɪvələnt/', exampleSentence: 'Equivalent value.', imageEmoji: '=', category: 'SAT' },
    { id: 'sat-324', word: 'Exhibit', definition: 'show', pronunciation: '/ɪɡˈzɪbɪt/', exampleSentence: 'Exhibit art.', imageEmoji: '🖼️', category: 'SAT' },
    { id: 'sat-325', word: 'External', definition: 'outside', pronunciation: '/ɪkˈstɜːrnl/', exampleSentence: 'External drive.', imageEmoji: '📤', category: 'SAT' },
    { id: 'sat-326', word: 'Finite', definition: 'has an end', pronunciation: '/ˈfaɪnaɪt/', exampleSentence: 'Finite supply.', imageEmoji: '⏳', category: 'SAT' },
    { id: 'sat-327', word: 'Implicit', definition: 'not said directly', pronunciation: '/ɪmˈplɪsɪt/', exampleSentence: 'Implicit meaning.', imageEmoji: '😉', category: 'SAT' },
    { id: 'sat-328', word: 'Induce', definition: 'cause', pronunciation: '/ɪnˈduːs/', exampleSentence: 'Induce sleep.', imageEmoji: '😴', category: 'SAT' },
    { id: 'sat-329', word: 'Invariant', definition: 'not changing', pronunciation: '/ɪnˈveriənt/', exampleSentence: 'Invariant rule.', imageEmoji: '🗿', category: 'SAT' },
    { id: 'sat-330', word: 'Magnitude', definition: 'size', pronunciation: '/ˈmæɡnɪtuːd/', exampleSentence: 'Great magnitude.', imageEmoji: '📏', category: 'SAT' },
    { id: 'sat-331', word: 'Norm', definition: 'usual rule', pronunciation: '/nɔːrm/', exampleSentence: 'Social norm.', imageEmoji: '📋', category: 'SAT' },
    { id: 'sat-332', word: 'Offset', definition: 'balance', pronunciation: '/ˈɔːfset/', exampleSentence: 'Offset the cost.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-333', word: 'Paradigm', definition: 'model', pronunciation: '/ˈpærədaɪm/', exampleSentence: 'New paradigm.', imageEmoji: '🗺️', category: 'SAT' },
    { id: 'sat-334', word: 'Persistent', definition: 'keeps going', pronunciation: '/pərˈsɪstənt/', exampleSentence: 'Persistent rain.', imageEmoji: '🌧️', category: 'SAT' },
    { id: 'sat-335', word: 'Prevalent', definition: 'common', pronunciation: '/ˈprevələnt/', exampleSentence: 'Prevalent view.', imageEmoji: '👀', category: 'SAT' },
    { id: 'sat-336', word: 'Prospective', definition: 'future', pronunciation: '/prəˈspektɪv/', exampleSentence: 'Prospective buyer.', imageEmoji: '🔮', category: 'SAT' },
    { id: 'sat-337', word: 'Robust', definition: 'strong', pronunciation: '/roʊˈbʌst/', exampleSentence: 'Robust flavor.', imageEmoji: '💪', category: 'SAT' },
    { id: 'sat-338', word: 'Subtle', definition: 'hard to notice', pronunciation: '/ˈsʌtl/', exampleSentence: 'Subtle change.', imageEmoji: '🕵️', category: 'SAT' },
    { id: 'sat-339', word: 'Threshold', definition: 'starting point', pronunciation: '/ˈθreʃhoʊld/', exampleSentence: 'Pain threshold.', imageEmoji: '🚪', category: 'SAT' },
    { id: 'sat-340', word: 'Ubiquitous', definition: 'everywhere', pronunciation: '/juːˈbɪkwɪtəs/', exampleSentence: 'Ubiquitous phones.', imageEmoji: '📱', category: 'SAT' },
    { id: 'sat-341', word: 'Viable', definition: 'able to work', pronunciation: '/ˈvaɪəbl/', exampleSentence: 'Viable plan.', imageEmoji: '🌱', category: 'SAT' },
    { id: 'sat-342', word: 'Voluntary', definition: 'by choice', pronunciation: '/ˈvɑːlənteri/', exampleSentence: 'Voluntary work.', imageEmoji: '🙋', category: 'SAT' },
    { id: 'sat-343', word: 'Compatible', definition: 'works together', pronunciation: '/kəmˈpætəbl/', exampleSentence: 'Compatible parts.', imageEmoji: '🧩', category: 'SAT' },
    { id: 'sat-344', word: 'Concurrent', definition: 'same time', pronunciation: '/kənˈkɜːrənt/', exampleSentence: 'Concurrent events.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-345', word: 'Controversy', definition: 'big argument', pronunciation: '/ˈkɑːntrəvɜːrsi/', exampleSentence: 'Public controversy.', imageEmoji: '🗣️', category: 'SAT' },
    { id: 'sat-346', word: 'Discretion', definition: 'careful choice', pronunciation: '/dɪˈskreʃn/', exampleSentence: 'Use discretion.', imageEmoji: '🤐', category: 'SAT' },
    { id: 'sat-347', word: 'Equilibrium', definition: 'balance', pronunciation: '/ˌiːkwɪˈlɪbriəm/', exampleSentence: 'Market equilibrium.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-348', word: 'Explicit', definition: 'clearly said', pronunciation: '/ɪkˈsplɪsɪt/', exampleSentence: 'Explicit instruction.', imageEmoji: '📢', category: 'SAT' },
    { id: 'sat-349', word: 'Feasible', definition: 'possible', pronunciation: '/ˈfiːzəbl/', exampleSentence: 'Is it feasible?', imageEmoji: '👍', category: 'SAT' },
    { id: 'sat-350', word: 'Marginal', definition: 'small', pronunciation: '/ˈmɑːrdʒɪnl/', exampleSentence: 'Marginal cost.', imageEmoji: '🤏', category: 'SAT' },
    { id: 'sat-351', word: 'Moderate', definition: 'not too much', pronunciation: '/ˈmɑːdərət/', exampleSentence: 'Moderate amount.', imageEmoji: '🌤️', category: 'SAT' },
    { id: 'sat-352', word: 'Negligible', definition: 'very small', pronunciation: '/ˈneɡlɪdʒəbl/', exampleSentence: 'Negligible effect.', imageEmoji: '🐜', category: 'SAT' },
    { id: 'sat-353', word: 'Optimal', definition: 'best', pronunciation: '/ˈɑːptɪml/', exampleSentence: 'Optimal solution.', imageEmoji: '🌟', category: 'SAT' },
    { id: 'sat-354', word: 'Precede', definition: 'come before', pronunciation: '/prɪˈsiːd/', exampleSentence: 'A precedes B.', imageEmoji: '⬅️', category: 'SAT' },
    { id: 'sat-355', word: 'Sole', definition: 'only', pronunciation: '/soʊl/', exampleSentence: 'Sole survivor.', imageEmoji: '☝️', category: 'SAT' },
    { id: 'sat-356', word: 'Absolute', definition: 'complete', pronunciation: '/ˈæbsəluːt/', exampleSentence: 'Absolute silence.', imageEmoji: '💯', category: 'SAT' },
    { id: 'sat-357', word: 'Consistent', definition: 'same each time', pronunciation: '/kənˈsɪstənt/', exampleSentence: 'Consistent effort.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-358', word: 'Appropriate', definition: 'right for situation', pronunciation: '/əˈproʊpriət/', exampleSentence: 'Appropriate dress.', imageEmoji: '👗', category: 'SAT' },
    { id: 'sat-359', word: 'Enable', definition: 'allow', pronunciation: '/ɪˈneɪbl/', exampleSentence: 'Enable the feature.', imageEmoji: '🔓', category: 'SAT' },
    { id: 'sat-360', word: 'Illustrate', definition: 'show with example', pronunciation: '/ˈɪləstreɪt/', exampleSentence: 'Illustrate the point.', imageEmoji: '🖍️', category: 'SAT' },
    { id: 'sat-361', word: 'Promote', definition: 'help grow', pronunciation: '/prəˈmoʊt/', exampleSentence: 'Promote health.', imageEmoji: '📢', category: 'SAT' },
    { id: 'sat-362', word: 'Sustainability', definition: 'lasting long', pronunciation: '/səˌsteɪnəˈbɪləti/', exampleSentence: 'Sustainability goal.', imageEmoji: '🌍', category: 'SAT' },
    { id: 'sat-363', word: 'Economy', definition: 'money system', pronunciation: '/ɪˈkɑːnəmi/', exampleSentence: 'Global economy.', imageEmoji: '💸', category: 'SAT' },
    { id: 'sat-364', word: 'Environment', definition: 'surroundings', pronunciation: '/ɪnˈvaɪrənmənt/', exampleSentence: 'Protect the environment.', imageEmoji: '🌳', category: 'SAT' },
    { id: 'sat-365', word: 'Hypothesis', definition: 'test idea', pronunciation: '/haɪˈpɑːθəsɪs/', exampleSentence: 'Scientific hypothesis.', imageEmoji: '🧪', category: 'SAT' },
    { id: 'sat-366', word: 'Immigrate', definition: 'move countries', pronunciation: '/ˈɪmɪɡreɪt/', exampleSentence: 'Immigrate to US.', imageEmoji: '✈️', category: 'SAT' },
    { id: 'sat-367', word: 'Labor', definition: 'work', pronunciation: '/ˈleɪbər/', exampleSentence: 'Hard labor.', imageEmoji: '👷', category: 'SAT' },
    { id: 'sat-368', word: 'Legal', definition: 'allowed', pronunciation: '/ˈliːɡl/', exampleSentence: 'Legal action.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-369', word: 'Domestic', definition: 'within country', pronunciation: '/dəˈmestɪk/', exampleSentence: 'Domestic flight.', imageEmoji: '🏠', category: 'SAT' },
    { id: 'sat-370', word: 'Decade', definition: 'ten years', pronunciation: '/ˈdekeɪd/', exampleSentence: 'Past decade.', imageEmoji: '📅', category: 'SAT' },
    { id: 'sat-371', word: 'Distribution', definition: 'how spread out', pronunciation: '/ˌdɪstrɪˈbjuːʃn/', exampleSentence: 'Wealth distribution.', imageEmoji: '🌍', category: 'SAT' },
    { id: 'sat-372', word: 'Estimate', definition: 'smart guess', pronunciation: '/ˈestɪmət/', exampleSentence: 'Rough estimate.', imageEmoji: '🤔', category: 'SAT' },
    { id: 'sat-373', word: 'Expose', definition: 'show', pronunciation: '/ɪkˈspoʊz/', exampleSentence: 'Expose the truth.', imageEmoji: '📸', category: 'SAT' },
    { id: 'sat-374', word: 'Feature', definition: 'key part', pronunciation: '/ˈfiːtʃər/', exampleSentence: 'Key feature.', imageEmoji: '⭐', category: 'SAT' },
    { id: 'sat-375', word: 'Flexible', definition: 'can bend or change', pronunciation: '/ˈfleksəbl/', exampleSentence: 'Flexible schedule.', imageEmoji: '🤸', category: 'SAT' },
    { id: 'sat-376', word: 'Global', definition: 'worldwide', pronunciation: '/ˈɡloʊbl/', exampleSentence: 'Global warming.', imageEmoji: '🌍', category: 'SAT' },
    { id: 'sat-377', word: 'Innovation', definition: 'new idea', pronunciation: '/ˌɪnəˈveɪʃn/', exampleSentence: 'Tech innovation.', imageEmoji: '💡', category: 'SAT' },
    { id: 'sat-378', word: 'Journal', definition: 'record', pronunciation: '/ˈdʒɜːrnl/', exampleSentence: 'Keep a journal.', imageEmoji: '📓', category: 'SAT' },
    { id: 'sat-379', word: 'Layer', definition: 'level', pronunciation: '/ˈleɪər/', exampleSentence: 'Layer of cake.', imageEmoji: '🍰', category: 'SAT' },
    { id: 'sat-380', word: 'Locate', definition: 'find', pronunciation: '/ˈloʊkeɪt/', exampleSentence: 'Locate the map.', imageEmoji: '📍', category: 'SAT' },
    { id: 'sat-381', word: 'Majority', definition: 'more than half', pronunciation: '/məˈdʒɔːrəti/', exampleSentence: 'The majority voted.', imageEmoji: '✋', category: 'SAT' },
    { id: 'sat-382', word: 'Maximum', definition: 'highest', pronunciation: '/ˈmæksɪməm/', exampleSentence: 'Maximum speed.', imageEmoji: '🔝', category: 'SAT' },
    { id: 'sat-383', word: 'Minimum', definition: 'lowest', pronunciation: '/ˈmɪnɪməm/', exampleSentence: 'Minimum wage.', imageEmoji: '⬇️', category: 'SAT' },
    { id: 'sat-384', word: 'Neutral', definition: 'not choosing sides', pronunciation: '/ˈnuːtrəl/', exampleSentence: 'Stay neutral.', imageEmoji: '😐', category: 'SAT' },
    { id: 'sat-385', word: 'Objective', definition: 'goal', pronunciation: '/əbˈdʒektɪv/', exampleSentence: 'Main objective.', imageEmoji: '🎯', category: 'SAT' },
    { id: 'sat-386', word: 'Outcome', definition: 'result', pronunciation: '/ˈaʊtkʌm/', exampleSentence: 'Good outcome.', imageEmoji: '🏁', category: 'SAT' },
    { id: 'sat-387', word: 'Primary', definition: 'main', pronunciation: '/ˈpraɪmeri/', exampleSentence: 'Primary cause.', imageEmoji: '☝️', category: 'SAT' },
    { id: 'sat-388', word: 'Procedure', definition: 'steps', pronunciation: '/prəˈsiːdʒər/', exampleSentence: 'Follow procedure.', imageEmoji: '📋', category: 'SAT' },
    { id: 'sat-389', word: 'Random', definition: 'no plan', pronunciation: '/ˈrændəm/', exampleSentence: 'Random choice.', imageEmoji: '🎲', category: 'SAT' },
    { id: 'sat-390', word: 'Recover', definition: 'get back', pronunciation: '/rɪˈkʌvər/', exampleSentence: 'Recover files.', imageEmoji: '🩹', category: 'SAT' },
    { id: 'sat-391', word: 'Resource', definition: 'useful thing', pronunciation: '/ˈriːsɔːrs/', exampleSentence: 'Natural resource.', imageEmoji: '💎', category: 'SAT' },
    { id: 'sat-392', word: 'Restrict', definition: 'limit', pronunciation: '/rɪˈstrɪkt/', exampleSentence: 'Restrict access.', imageEmoji: '🚧', category: 'SAT' },
    { id: 'sat-393', word: 'Scale', definition: 'size', pronunciation: '/skeɪl/', exampleSentence: 'Large scale.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-394', word: 'Shift', definition: 'change', pronunciation: '/ʃɪft/', exampleSentence: 'Night shift.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-395', word: 'Statistics', definition: 'number facts', pronunciation: '/stəˈtɪstɪks/', exampleSentence: 'Study statistics.', imageEmoji: '📊', category: 'SAT' },
    { id: 'sat-396', word: 'Substitute', definition: 'replace', pronunciation: '/ˈsʌbstɪtuːt/', exampleSentence: 'Substitute teacher.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-397', word: 'Summary', definition: 'short version', pronunciation: '/ˈsʌməri/', exampleSentence: 'Read the summary.', imageEmoji: '📝', category: 'SAT' },
    { id: 'sat-398', word: 'Temporary', definition: 'short time', pronunciation: '/ˈtempəreri/', exampleSentence: 'Temporary job.', imageEmoji: '⏳', category: 'SAT' },
    { id: 'sat-399', word: 'Transition', definition: 'change', pronunciation: '/trænˈzɪʃn/', exampleSentence: 'Make a transition.', imageEmoji: '🌉', category: 'SAT' },
    { id: 'sat-400', word: 'Valid', definition: 'true', pronunciation: '/ˈvælɪd/', exampleSentence: 'Valid point.', imageEmoji: '✅', category: 'SAT' },
    { id: 'sat-401', word: 'Visible', definition: 'can be seen', pronunciation: '/ˈvɪzəbl/', exampleSentence: 'Visible stars.', imageEmoji: '👁️', category: 'SAT' },
    { id: 'sat-402', word: 'Widespread', definition: 'many places', pronunciation: '/ˈwaɪdspred/', exampleSentence: 'Widespread panic.', imageEmoji: '🌍', category: 'SAT' },
    { id: 'sat-403', word: 'Accurate', definition: 'correct', pronunciation: '/ˈækjərət/', exampleSentence: 'Accurate news.', imageEmoji: '✅', category: 'SAT' },
    { id: 'sat-404', word: 'Alternative', definition: 'another option', pronunciation: '/ɔːlˈtɜːrnətɪv/', exampleSentence: 'Alternative route.', imageEmoji: '🛤️', category: 'SAT' },
    { id: 'sat-405', word: 'Assistance', definition: 'help', pronunciation: '/əˈsɪstəns/', exampleSentence: 'Need assistance?', imageEmoji: '🆘', category: 'SAT' },
    { id: 'sat-406', word: 'Authority', definition: 'power', pronunciation: '/əˈθɔːrəti/', exampleSentence: 'Person in authority.', imageEmoji: '👮', category: 'SAT' },
    { id: 'sat-407', word: 'Bias', definition: 'unfair idea', pronunciation: '/ˈbaɪəs/', exampleSentence: 'Personal bias.', imageEmoji: '🧠', category: 'SAT' },
    { id: 'sat-408', word: 'Category', definition: 'group', pronunciation: '/ˈkætəɡɔːri/', exampleSentence: 'Choose category.', imageEmoji: '📂', category: 'SAT' },
    { id: 'sat-409', word: 'Circumstance', definition: 'situation', pronunciation: '/ˈsɜːrkəmstæns/', exampleSentence: 'Bad circumstance.', imageEmoji: '🌩️', category: 'SAT' },
    { id: 'sat-410', word: 'Conflict', definition: 'disagreement', pronunciation: '/ˈkɑːnflɪkt/', exampleSentence: 'Avoid conflict.', imageEmoji: '🥊', category: 'SAT' },
    { id: 'sat-411', word: 'Consequence', definition: 'result', pronunciation: '/ˈkɑːnsɪkwens/', exampleSentence: 'Face consequence.', imageEmoji: '⚠️', category: 'SAT' },
    { id: 'sat-412', word: 'Definite', definition: 'clear', pronunciation: '/ˈdefɪnət/', exampleSentence: 'Definite answer.', imageEmoji: '👍', category: 'SAT' },
    { id: 'sat-413', word: 'Element', definition: 'part', pronunciation: '/ˈelɪmənt/', exampleSentence: 'Key element.', imageEmoji: '⚛️', category: 'SAT' },
    { id: 'sat-414', word: 'Eventually', definition: 'later', pronunciation: '/ɪˈventʃuəli/', exampleSentence: 'Eventually arrived.', imageEmoji: '🏁', category: 'SAT' },
    { id: 'sat-415', word: 'Foundation', definition: 'base', pronunciation: '/faʊnˈdeɪʃn/', exampleSentence: 'Strong foundation.', imageEmoji: '🧱', category: 'SAT' },
    { id: 'sat-416', word: 'Guideline', definition: 'rule', pronunciation: '/ˈɡaɪdlaɪn/', exampleSentence: 'Follow the guideline.', imageEmoji: '📏', category: 'SAT' },
    { id: 'sat-417', word: 'Illustrate', definition: 'show', pronunciation: '/ˈɪləstreɪt/', exampleSentence: 'Illustrate the point.', imageEmoji: '🖍️', category: 'SAT' },
    { id: 'sat-418', word: 'Instance', definition: 'example', pronunciation: '/ˈɪnstəns/', exampleSentence: 'Single instance.', imageEmoji: '👆', category: 'SAT' },
    { id: 'sat-419', word: 'Interaction', definition: 'working together', pronunciation: '/ˌɪntərˈækʃn/', exampleSentence: 'Interaction design.', imageEmoji: '🖱️', category: 'SAT' },
    { id: 'sat-420', word: 'Logic', definition: 'clear thinking', pronunciation: '/ˈlɑːdʒɪk/', exampleSentence: 'Use logic.', imageEmoji: '🧠', category: 'SAT' },
    { id: 'sat-421', word: 'Mechanism', definition: 'how something works', pronunciation: '/ˈmekənɪzm/', exampleSentence: 'Complex mechanism.', imageEmoji: '⚙️', category: 'SAT' },
    { id: 'sat-422', word: 'Network', definition: 'connected system', pronunciation: '/ˈnetwɜːrk/', exampleSentence: 'Computer network.', imageEmoji: '🌐', category: 'SAT' },
    { id: 'sat-423', word: 'Outcome', definition: 'result', pronunciation: '/ˈaʊtkʌm/', exampleSentence: 'Final outcome.', imageEmoji: '🏁', category: 'SAT' },
    { id: 'sat-424', word: 'Perspective', definition: 'point of view', pronunciation: '/pərˈspektɪv/', exampleSentence: 'My perspective.', imageEmoji: '👀', category: 'SAT' },
    { id: 'sat-425', word: 'Potential', definition: 'possible', pronunciation: '/pəˈtenʃl/', exampleSentence: 'High potential.', imageEmoji: '🚀', category: 'SAT' },
    { id: 'sat-426', word: 'Principle', definition: 'rule', pronunciation: '/ˈprɪnsəpl/', exampleSentence: 'Moral principle.', imageEmoji: '📜', category: 'SAT' },
    { id: 'sat-427', word: 'Regulate', definition: 'control', pronunciation: '/ˈreɡjuleɪt/', exampleSentence: 'Regulate prices.', imageEmoji: '🎛️', category: 'SAT' },
    { id: 'sat-428', word: 'Scenario', definition: 'situation', pronunciation: '/səˈnerioʊ/', exampleSentence: 'Best scenario.', imageEmoji: '🎬', category: 'SAT' },
    { id: 'sat-429', word: 'Sector', definition: 'part', pronunciation: '/ˈsektər/', exampleSentence: 'Public sector.', imageEmoji: '🏢', category: 'SAT' },
    { id: 'sat-430', word: 'Simultaneous', definition: 'same time', pronunciation: '/ˌsaɪmlˈteɪniəs/', exampleSentence: 'Simultaneous events.', imageEmoji: '🕒', category: 'SAT' },
    { id: 'sat-431', word: 'Stance', definition: 'opinion', pronunciation: '/stæns/', exampleSentence: 'Take a stance.', imageEmoji: '🦶', category: 'SAT' },
    { id: 'sat-432', word: 'Stimulate', definition: 'encourage', pronunciation: '/ˈstɪmjuleɪt/', exampleSentence: 'Stimulate growth.', imageEmoji: '🌱', category: 'SAT' },
    { id: 'sat-433', word: 'Subsequent', definition: 'after', pronunciation: '/ˈsʌbsɪkwənt/', exampleSentence: 'Subsequent events.', imageEmoji: '⏭️', category: 'SAT' },
    { id: 'sat-434', word: 'Sufficient', definition: 'enough', pronunciation: '/səˈfɪʃnt/', exampleSentence: 'Sufficient funds.', imageEmoji: '🍲', category: 'SAT' },
    { id: 'sat-435', word: 'Target', definition: 'goal', pronunciation: '/ˈtɑːrɡɪt/', exampleSentence: 'Hit the target.', imageEmoji: '🎯', category: 'SAT' },
    { id: 'sat-436', word: 'Underlying', definition: 'hidden cause', pronunciation: '/ˌʌndərˈlaɪɪŋ/', exampleSentence: 'Underlying issue.', imageEmoji: '👇', category: 'SAT' },
    { id: 'sat-437', word: 'Uniform', definition: 'same', pronunciation: '/ˈjuːnɪfɔːrm/', exampleSentence: 'Uniform size.', imageEmoji: '👮', category: 'SAT' },
    { id: 'sat-438', word: 'Utilize', definition: 'use', pronunciation: '/ˈjuːtəlaɪz/', exampleSentence: 'Utilize resources.', imageEmoji: '🛠️', category: 'SAT' },
    { id: 'sat-439', word: 'Verify', definition: 'check', pronunciation: '/ˈverɪfaɪ/', exampleSentence: 'Verify data.', imageEmoji: '✅', category: 'SAT' },
    { id: 'sat-440', word: 'Violate', definition: 'break rule', pronunciation: '/ˈvaɪəleɪt/', exampleSentence: 'Violate terms.', imageEmoji: '🚫', category: 'SAT' },
    { id: 'sat-441', word: 'Welfare', definition: 'well-being', pronunciation: '/ˈwelfer/', exampleSentence: 'Social welfare.', imageEmoji: '🏥', category: 'SAT' },
    { id: 'sat-442', word: 'Aggregate', definition: 'total', pronunciation: '/ˈæɡrɪɡət/', exampleSentence: 'Aggregate amount.', imageEmoji: '∑', category: 'SAT' },
    { id: 'sat-443', word: 'Allocate', definition: 'give out', pronunciation: '/ˈæləkeɪt/', exampleSentence: 'Allocate time.', imageEmoji: '💸', category: 'SAT' },
    { id: 'sat-444', word: 'Coherent', definition: 'clear', pronunciation: '/koʊˈhɪrənt/', exampleSentence: 'Coherent plan.', imageEmoji: '🗣️', category: 'SAT' },
    { id: 'sat-445', word: 'Constraint', definition: 'limit', pronunciation: '/kənˈstreɪnt/', exampleSentence: 'Time constraint.', imageEmoji: '⛓️', category: 'SAT' },
    { id: 'sat-446', word: 'Correlation', definition: 'link', pronunciation: '/ˌkɔːrəˈleɪʃn/', exampleSentence: 'Correlation between variables.', imageEmoji: '🔗', category: 'SAT' },
    { id: 'sat-447', word: 'Equivalent', definition: 'equal', pronunciation: '/ɪˈkwɪvələnt/', exampleSentence: 'Equivalent weight.', imageEmoji: '=', category: 'SAT' },
    { id: 'sat-448', word: 'Explicit', definition: 'clearly said', pronunciation: '/ɪkˈsplɪsɪt/', exampleSentence: 'Explicit detail.', imageEmoji: '📢', category: 'SAT' },
    { id: 'sat-449', word: 'Feasible', definition: 'possible', pronunciation: '/ˈfiːzəbl/', exampleSentence: 'Feasible idea.', imageEmoji: '👍', category: 'SAT' },
    { id: 'sat-450', word: 'Magnitude', definition: 'size', pronunciation: '/ˈmæɡnɪtuːd/', exampleSentence: 'Magnitude of event.', imageEmoji: '📏', category: 'SAT' },
    { id: 'sat-451', word: 'Norm', definition: 'usual rule', pronunciation: '/nɔːrm/', exampleSentence: 'Cultural norm.', imageEmoji: '📋', category: 'SAT' },
    { id: 'sat-452', word: 'Persistent', definition: 'keeps trying', pronunciation: '/pərˈsɪstənt/', exampleSentence: 'Persistent effort.', imageEmoji: '🌧️', category: 'SAT' },
    { id: 'sat-453', word: 'Prevalent', definition: 'common', pronunciation: '/ˈprevələnt/', exampleSentence: 'Prevalent attitude.', imageEmoji: '👀', category: 'SAT' },
    { id: 'sat-454', word: 'Robust', definition: 'strong', pronunciation: '/roʊˈbʌst/', exampleSentence: 'Robust economy.', imageEmoji: '💪', category: 'SAT' },
    { id: 'sat-455', word: 'Subtle', definition: 'hard to see', pronunciation: '/ˈsʌtl/', exampleSentence: 'Subtle diff.', imageEmoji: '🕵️', category: 'SAT' },
    { id: 'sat-456', word: 'Threshold', definition: 'starting point', pronunciation: '/ˈθreʃhoʊld/', exampleSentence: 'Low threshold.', imageEmoji: '🚪', category: 'SAT' },
    { id: 'sat-457', word: 'Ubiquitous', definition: 'everywhere', pronunciation: '/juːˈbɪkwɪtəs/', exampleSentence: 'Ubiquitous internet.', imageEmoji: '📱', category: 'SAT' },
    { id: 'sat-458', word: 'Viable', definition: 'works', pronunciation: '/ˈvaɪəbl/', exampleSentence: 'Viable option.', imageEmoji: '🌱', category: 'SAT' },
    { id: 'sat-459', word: 'Voluntary', definition: 'by choice', pronunciation: '/ˈvɑːlənteri/', exampleSentence: 'Voluntary service.', imageEmoji: '🙋', category: 'SAT' },
    { id: 'sat-460', word: 'Compatible', definition: 'fits together', pronunciation: '/kəmˈpætəbl/', exampleSentence: 'Compatible types.', imageEmoji: '🧩', category: 'SAT' },
    { id: 'sat-461', word: 'Concurrent', definition: 'same time', pronunciation: '/kənˈkɜːrənt/', exampleSentence: 'Concurrent lines.', imageEmoji: '🔄', category: 'SAT' },
    { id: 'sat-462', word: 'Controversy', definition: 'big argument', pronunciation: '/ˈkɑːntrəvɜːrsi/', exampleSentence: 'Caused controversy.', imageEmoji: '🗣️', category: 'SAT' },
    { id: 'sat-463', word: 'Equilibrium', definition: 'balance', pronunciation: '/ˌiːkwɪˈlɪbriəm/', exampleSentence: 'Restore equilibrium.', imageEmoji: '⚖️', category: 'SAT' },
    { id: 'sat-464', word: 'Marginal', definition: 'small', pronunciation: '/ˈmɑːrdʒɪnl/', exampleSentence: 'Marginal gain.', imageEmoji: '🤏', category: 'SAT' },
    { id: 'sat-465', word: 'Moderate', definition: 'not too much', pronunciation: '/ˈmɑːdərət/', exampleSentence: 'Moderate breeze.', imageEmoji: '🌤️', category: 'SAT' },
    { id: 'sat-466', word: 'Optimal', definition: 'best', pronunciation: '/ˈɑːptɪml/', exampleSentence: 'Optimal path.', imageEmoji: '🌟', category: 'SAT' },
    { id: 'sat-467', word: 'Precede', definition: 'come before', pronunciation: '/prɪˈsiːd/', exampleSentence: 'Precede the act.', imageEmoji: '⬅️', category: 'SAT' },
    { id: 'sat-468', word: 'Sole', definition: 'only', pronunciation: '/soʊl/', exampleSentence: 'Sole purpose.', imageEmoji: '☝️', category: 'SAT' },
    { id: 'sat-469', word: 'Sustainability', definition: 'lasting long', pronunciation: '/səˌsteɪnəˈbɪləti/', exampleSentence: 'Sustainability.', imageEmoji: '🌍', category: 'SAT' },
];

